#!/usr/bin/env python3
# -*- coding: utf-8 -*-

def apply():
    file_path = 'main_menu/localization/english/laws_and_policies_l_english.yml'

    m = {
        1692: ' mamluk_rank_system_laws: "Мамлюцька система рангів"\n',
        1693: ' mamluk_rank_system_laws_desc: "Ієрархія в наших збройних силах — це основа найважливішої інституції держави."\n',
        1694: ' mam_rigid_system: "Жорстка система"\n',
        1695: ' mam_rigid_system_desc: "Взявши за основу жорстку ієрархію, ми домож\' того, що всі мамлюки, від новобранців до ветеранів, займатимуться вдосконаленням своїх навичок, а не погонею за підвищенням по службі."\n',
        1696: ' mam_fluid_system: "Гнучка система"\n',
        1697: ' mam_fluid_system_desc: "Гнучка система рангів призведе до того, що воїни відчуватимуть себе частиною наших збройних сил. Привабливість росту і просування по армійській ієрархії — чудовий стимул для тих, хто вирвався з убогості або кабали."\n',
        1698: ' mam_refined_furusiyya: "Переглянута фурусія"\n',
        1699: ' mam_refined_furusiyya_desc: "Століттями ми вдосконалювали фурусію, #L [ShowReligionGroupAdjective(\'muslim\')|l]ий#! звід правил лицарської доблесті і військової майстерності, в якому мистецтво верхової їзди, стрільби з лука і тактики бою поєднується з інтелектуальним розвитком і моральним вихованням."\n',
        1700: ' mamluk_army_law: "Закон про мамлюцьку армію"\n',
        1701: ' mamluk_army_law_desc: "Армія — це серце нашої стратократичної влади. Тільки розробивши закони і положення, що ретельно регулюють порядок її формування, ми зможемо захистити наш народ від зовнішніх загроз."\n',
        1702: ' al_mamalik_al_sultaniyya: "Аль-Мамалік аль-Султанійя"\n',
        1703: ' al_mamalik_al_sultaniyya_desc: "Якщо возвеличувати лише мамлюків, що перебувають на службі в султана, ми зможемо забезпечити дисципліну і ефективність наших елітних військ."\n',
        1704: ' mamalik_al_umara: "Мамалік аль-Умара"\n',
        1705: ' mamalik_al_umara_desc: "$mamluks$, які служать під началом еміра, — це чудове джерело міцних бійців для поповнення наших військ."\n',
        1706: ' ajnad_al_halqa: "Аджнад аль-Халька"\n',
        1707: ' ajnad_al_halqa_desc: "Армія не може належним чином існувати без сильних допоміжних військ і надійної інтендантської служби."\n',
        1708: ' awlad_al_nas_policy: "Аулад аль-Нас"\n',
        1709: ' awlad_al_nas_policy_desc: "Незважаючи на обов\'язкове звернення до ісламу і процедуру звільнення з рабства, через які пройшли старі мамлюки, вони, схоже, постійно намагаються підірвати центральну владу. Необхідно сформувати новий корпус, воїнів якого тренуватимуть і навчатимуть по-іншому."\n',
        1710: ' mamluk_promotion_law: "Закон про просування мамлюків"\n',
        1711: ' mamluk_promotion_law_desc: "Закони, що регулюють просування по службі в лавах нашої армії, є наріжним каменем нашої держави."\n',
        1712: ' merit_basis: "На основі заслуг"\n',
        1713: ' merit_basis_desc: "Просування по службі на основі заслуг — це відмінний спосіб відібрати талановитих і сильних воїнів, незважаючи на їхнє становище і походження."\n',
        1714: ' origin_basis: "На основі походження"\n',
        1715: ' origin_basis_desc: "Віддаючи перевагу воїнам одного етнічного походження, ми зможемо отримати згуртовану армію, яка має спільне почуття гордості."\n',
        1716: ' dynastic_basis: "На основі спорідненості"\n',
        1717: ' dynastic_basis_desc: "Військові посади в нашій армії можуть передаватися від батька до сина, стверджуючи спадкоємність і легітимність престолонаслідування."\n',
        1718: ' employment_system: "$game_concept_employment_system$"\n',
        1719: ' employment_system_desc: "$game_concept_employment_system_desc$"\n',
        1720: ' first_come_first_serve_policy: "$first_come_first_serve$"\n',
        1721: ' first_come_first_serve_policy_desc: "$first_come_first_serve_desc$"\n',
        1722: ' equality_policy: "$equality$"\n',
        1723: ' equality_policy_desc: "$equality_desc$"\n',
        1724: ' capitalism_policy: "$capitalism$"\n',
        1725: ' capitalism_policy_desc: "$capitalism_desc$"\n',
        1727: ' io_policy_vote_active_cooldown: "Міжнародне голосування зі зміни політики"\n',
        1728: ' sc_policy_proposal_frequency: "Частота пропозицій з політики"\n',
        1729: ' sc_policy_proposal_frequency_desc: "Правило адміністрування законопроектів у #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарській конфедерації#!#!."\n',
        1730: ' sc_frequent_policy_proposals: "Часті пропозиції з політики"\n',
        1731: ' sc_frequent_policy_proposals_desc: "Зміна правил і політик — часте явище, що відбувається в #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарській конфедерації#!#! кожні 4 роки."\n',
        1732: ' sc_moderate_policy_proposals: "Помірні пропозиції з політики"\n',
        1733: ' sc_moderate_policy_proposals_desc: "Хоча це і важливий процес, адміністрування законів і пропозицій з політики в #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарській конфедерації#!#! потребує значних зусиль, тому законопроекти вносяться лише раз на 8 років."\n',
        1734: ' sc_religious_affairs: "Релігійні справи"\n',
        1735: ' sc_religious_affairs_desc: "[ShowSituationName(\'reformation\')] набирає обертів, через що релігійна єдність конфедерації перебуває в хиткому становищі. Необхідно вирішити цю проблему, інакше конфлікт віри загрожує розірвати унію на частини."\n',
        1736: ' sc_clear_religious_chaos_tt: "[ShowLawName(\'sc_internal_politics\')] і [ShowLawName(\'sc_war_politics\')|l] тепер поширюються на всіх учасників, незалежно від їхньої [Concept(\'religion\', \'віри\')|e]."\n',
        1737: ' sc_mending_schism: "Виправлення розколу"\n',
        1738: ' sc_mending_schism_desc: "Стабільність і безпека #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! вище релігійних чвар #TOOLTIP:SITUATION,reformation,X #L Католицької Реформації#!#!. Усі учасники мають утриматися від ворожнечі через віру."\n',
        1739: ' sc_enforcing_religious_unity: "Встановлення релігійної єдності"\n',
        1740: ' sc_enforcing_religious_unity_desc: "Віра відіграє важливу роль у житті учасників #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#!, а тому її релігійна єдність має першорядне значення. Усі кантони мають так чи інакше дотримуватися однієї і тієї самої віри."\n',
        1741: ' sc_only_defending_same_religion_allies_tt: "Поточна #TOOLTIP:LAW,sc_war_politics,X #L військова політика#!#! іде на користь лише учасникам, які дотримуються однієї віри."\n',
        1742: ' sc_relations_with_hre: "Імперські відносини"\n',
        1743: ' sc_relations_with_hre_desc: "#TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарська конфедерація#!#! є частиною #ONCLICK:INTERNATIONAL_ORGANIZATION,hre #TOOLTIP:INTERNATIONAL_ORGANIZATION,hre,X #L Священної Римської імперії#!#! з моменту свого створення. Проте #TOOLTIP:SITUATION,reformation,X #L Католицька Реформація#!#! викликала невдоволення у багатьох учасників конфедерації…"\n',
        1744: ' sc_remain_in_the_hre: "Залишатися в імперії"\n',
        1745: ' sc_remain_in_the_hre_desc: "Хоча #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарська конфедерація#!#! — успішне об\'єднання, здатне захистити своїх учасників від іноземних держав, але воно погано підходить для протистояння військовій міці набагато більших держав. Залишаючись у #ONCLICK:INTERNATIONAL_ORGANIZATION,hre #TOOLTIP:INTERNATIONAL_ORGANIZATION,hre,X #L Священній Римській імперії#!#!, ми надамо #TOOLTIP:CULTURE,$swiss_group_tt$,X #L швейцарському#!#! народу більше необхідної підтримки."\n',
        1746: ' sc_remain_in_the_hre_tt: "Залишатися в #ONCLICK:INTERNATIONAL_ORGANIZATION,hre #TOOLTIP:INTERNATIONAL_ORGANIZATION,hre,X #L Священній Римській імперії#!#!"\n',
        1747: ' sc_prestige_malus_tt: "Кожен учасник втрачає [ShowNamedValue(\'prestige_extreme_penalty\')|+=2%] од. [Concept(\'prestige\', \'престижу\')|e]"\n',
        1748: ' sc_leave_the_hre: "Покинути імперію"\n',
        1749: ' sc_leave_the_hre_desc: "Хоча зовнішні вороги не рідкість, найбільші загрози для #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! йдуть зсередини самої #ONCLICK:INTERNATIONAL_ORGANIZATION,hre #TOOLTIP:INTERNATIONAL_ORGANIZATION,hre,X #L Священної Римської імперії#!#!, що обіцяла захищати своїх учасників. Залишаючись в імперії, ми лише піддаємося ризику."\n',
        1750: ' sc_leave_the_hre_tt: "Покинути #ONCLICK:INTERNATIONAL_ORGANIZATION,hre #TOOLTIP:INTERNATIONAL_ORGANIZATION,hre,X #L Священну Римську імперію#!#!"\n',
        1751: ' sc_every_member_leaves_hre_tt: "Усі учасники покидають #ONCLICK:INTERNATIONAL_ORGANIZATION,hre #TOOLTIP:INTERNATIONAL_ORGANIZATION,hre,X #L Священну Римську імперію#!#! і не зможуть більше до неї приєднатися, поки залишаються учасниками #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#!"\n',
        1752: ' sc_representative: "#L [ShowCultureGroupNameWithNoTooltip(\'swiss_group\')]ий#! представник"\n',
        1753: ' sc_representative_desc: "Кожному виду організації потрібен спікер — представник, який буде обличчям політичних суб\'єктів всередині і за межами організації. Проте #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарська конфедерація#!#! може бути винятком з цього правила…"\n',
        1754: ' sc_canton_representative: "Представник-кантон"\n',
        1755: ' sc_canton_representative_desc: "Деякі кантони багатші або впливовіші за інших. Таким чином, #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарську конфедерацію#!#! представлятиме не людина, а місто-держава."\n',
        1756: ' sc_councillor_representative: "Радник-представник"\n',
        1757: ' sc_councillor_representative_desc: "Кантонам #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! слід відмовитися від частини свого впливу і призначити одну людину обличчям конфедерації."\n',
        1758: ' sc_power_of_the_sovereign: "На чолі конфедерації стоїть [GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle]"\n',
        1759: ' sc_power_of_the_sovereign_desc: "Представник конфедерації міг би зажадати більше повноважень і впливу в унії, щоб зміцнити свої позиції на громадській арені."\n',
        1760: ' sc_sovereign_representative_power: "Представницька влада"\n',
        1761: ' sc_sovereign_representative_power_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] має право попросити допомоги в учасників #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! з різних питань, починаючи від фінансової допомоги і закінчуючи військовою підтримкою."\n',
        1762: ' sc_sovereign_religious_power: "Релігійна влада"\n',
        1763: ' sc_sovereign_religious_power_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] не має широких повноважень і завідує лише релігійними справами #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#!."\n',
        1764: ' sc_sovereign_absolute_power: "Абсолютна влада"\n',
        1765: ' sc_sovereign_absolute_power_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] керує #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарською конфедерацією#!#! як єдиною державою. Таким чином, правитель користується всіма привілеями і виконує всі обов\'язки, як ніби він був монархом конфедерації."\n',
        1766: ' sc_election_method: "Система виборів"\n',
        1767: ' sc_election_method_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! обирається за належним рішенням з боку відповідного законодавчого органу."\n',
        1768: ' sc_direct_vote: "Пряме голосування"\n',
        1769: ' sc_direct_vote_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] обирається напряму учасниками #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#!. Кожен учасник має один голос і право представляти конфедерацію."\n',
        1770: ' sc_lottery: "Жеребкування"\n',
        1771: ' sc_lottery_desc: "Тільки Господь Бог може вирішувати, хто представлятиме #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарську конфедерацію#!#!. Вибори здійснюються через таємне жеребкування, вирішальним чинником в якому є доля."\n',
        1772: ' sc_rotation: "Чергування"\n',
        1773: ' sc_rotation_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] призначається по черзі. Кожен учасник #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! має представляти конфедерацію хоча б раз, перш ніж колишній лідер зможе знову отримати владу."\n',
        1774: ' sc_ruling_period: "Період правління"\n',
        1775: ' sc_ruling_period_desc: "У конфедерації може бути [GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle]. Проте потрібно визначити чи [GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] служитиме унії довічно або протягом певного часу."\n',
        1776: ' sc_timed: "Тимчасове лідерство"\n',
        1777: ' sc_timed_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! перебуває при владі лише протягом встановленого періоду. Після цього термін повноважень минає, і обирається новий [GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle|l]."\n',
        1778: ' sc_lifelong: "Довічне лідерство"\n',
        1779: ' sc_lifelong_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! служить їй все життя. Вибори проводяться лише після смерті або примусової відставки правителя."\n',
        1780: ' sc_election_frequency: "Частота виборів"\n',
        1781: ' sc_election_frequency_desc: "Тепер, коли [ShowLawName(\'sc_ruling_period\')|l] визначений, перейдемо до наступного питання — частоти проведення виборів, на яких обиратиметься новий [GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle]."\n',
        1782: ' sc_biyearly_elections: "Вибори раз на два роки"\n',
        1783: ' sc_biyearly_elections_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! обирається кожні 2 роки."\n',
        1784: ' sc_four_yearly_elections: "Вибори раз на 4 роки"\n',
        1785: ' sc_four_yearly_elections_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! обирається кожні 4 роки."\n',
        1786: ' sc_eight_yearly_elections: "Вибори раз на 8 років"\n',
        1787: ' sc_eight_yearly_elections_desc: "[GetUniqueInternationalOrganization(\'swiss_confederation\').GetLeaderTitle] #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! обирається кожні 8 років."\n',
        1788: ' sc_internal_politics: "Внутрішня політика"\n',
        1789: ' sc_internal_politics_desc: "Хоча #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарська конфедерація#!#! — це насамперед союз, створений в оборонних цілях, очевидно, що внутрішні справи конфедерації також мають вирішуватися спільними силами."\n',
        1790: ' sc_forbid_internal_wars: "Заборона на внутрішні війни"\n',
        1791: ' sc_forbid_internal_wars_desc: "Не можна допустити, щоб дрібні суперечки переросли в криваві конфлікти. Кожен учасник #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! має вирішувати свої проблеми з іншим учасником за допомогою суддів конфедерації, а не на полі бою."\n',
        1792: ' sc_forbid_internal_wars_tt: "Жоден учасник #ONCLICK:INTERNATIONAL_ORGANIZATION,swiss_confederation #TOOLTIP:INTERNATIONAL_ORGANIZATION,swiss_confederation,X #L Швейцарської Конфедерації#!#! не може атакувати іншого учасника"\n',
        1793: ' sc_forbid_same_religion_internal_wars_tt: "Жоден учасник #ONCLICK:INTERNATIONAL_ORGANIZATION,swiss_confederation #TOOLTIP:INTERNATIONAL_ORGANIZATION,swiss_confederation,X #L Швейцарської Конфедерації#!#! не може атакувати іншого учасника, що сповідує одну з ним [Concept(\'religion\',\'віру\')|e]"\n',
        1794: ' sc_allow_internal_wars: "Дозволені внутрішні війни"\n',
        1795: ' sc_allow_internal_wars_desc: "Війни — невід\'ємна частина людської історії. Так, приємного в них мало, але будь-які конфлікти роблять нас сильнішими."\n',
        1796: ' sc_membership_regulation: "Регламентація членства"\n',
        1797: ' sc_membership_regulation_desc: "[GetInternationalOrganizationType(\'swiss_confederation\').GetName] спочатку створена #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарцями#!#! для захисту від династії Габсбургів, чий вплив у регіоні став занадто значним. Проте досі так і не вирішено, хто має право вступити до об\'єднання…"\n',
        1798: ' sc_swiss_culture_and_geography: "Тільки корінні швейцарці"\n',
        1799: ' sc_swiss_culture_and_geography_desc: "Конфедерація — суто #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарське#!#! об\'єднання, тому до неї можуть приєднатися лише держави конкретної культури і регіону."\n',
        1800: ' sc_swiss_culture_and_geography_tt: "Приєднатися до об\'єднання можуть лише держави зі #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарською#!#! культурою як [Concept(\'primary_culture\',\'основною\')|e]. При цьому їхня [Concept(\'capital\',\'столиця\')|e] має знаходитися в #TOOLTIP:AREA,central_switzerland_area,X #L центральній#!#!, #TOOLTIP:AREA,eastern_switzerland_area,X #L східній#!#! або #TOOLTIP:AREA,western_switzerland_area,X #L західній Швейцарії#!#!"\n',
        1801: ' sc_just_swiss_culture: "Швейцарська культура"\n',
        1802: ' sc_just_swiss_culture_desc: "Незважаючи на природні кордони, вплив #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарської#!#! культури поширюється далеко за межі Швейцарської Конфедерації. Тому варто переглянути закон про те, кому можна приєднуватися до об\'єднання."\n',
        1803: ' sc_just_swiss_culture_tt: "Приєднатися до об\'єднання можуть лише держави зі #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарською#!#! культурою як [Concept(\'primary_culture\',\'основною\')|e]"\n',
        1804: ' sc_swiss_or_swiss_relative: "Родичі швейцарців"\n',
        1805: ' sc_swiss_or_swiss_relative_desc: "[GetInternationalOrganizationType(\'swiss_confederation\').GetName] має велику міць і вплив не лише завдяки #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарцям#!#!, але й за рахунок внеску інших народів, близьких до нашої культури."\n',
        1806: ' sc_swiss_or_swiss_relative_tt: "Приєднатися до об\'єднання можуть лише держави, чия [Concept(\'primary_culture\',\'основна культура\')|e] або [Concept(\'language\',\'мова\')|e] є #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарськими#!#!"\n',
        1807: ' sc_war_politics: "Військова політика"\n',
        1808: ' sc_war_politics_desc: "У #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! багато зовнішніх загроз. #TOOLTIP:CULTUREGROUP,swiss_group,X #L Швейцарський#!#! народ має бути єдиний у захисті один одного — тоді конфедерація зможе вижити в оточуючій її політичній анархії."\n',
        1809: ' sc_defensive_pact: "Оборонний пакт"\n',
        1810: ' sc_defensive_pact_desc: "Учасники #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! покликатимуться до зброї лише в оборонній війні проти зовнішніх загроз."\n',
        1811: ' sc_alliance: "Швейцарський союз"\n',
        1812: ' sc_alliance_desc: "Учасники #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! можуть звертатися один до одного за допомогою в прагненні розширити свою територію. У разі зовнішнього вторгнення всі учасники покликаються до зброї, щоб захистити своїх товаришів по конфедерації."\n',
        1813: ' sc_united_war_efforts: "Спільні військові дії"\n',
        1814: ' sc_united_war_efforts_desc: "#TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарська конфедерація#!#! стає єдиним політичним центром для всіх зовнішніх держав. У кожній війні — наступальній або оборонній — мають брати участь військові сили всіх учасників конфедерації."\n',
        1815: ' sc_call_to_arms_conditions_tt: "[Custom(\'GetSCCallToArmsTooltip\')]"\n',
        1816: ' sc_call_to_arms_only_same_religion_tt: "$sc_call_to_arms_always_tt$, а сторона, що закликає, і закликані сповідують одну і ту саму [Concept(\'religion\', \'релігію\')|e]"\n',
        1817: ' sc_call_to_arms_always_tt: "Ворог НЕ є членом #TOOLTIP:INTERNATIONAL_ORGANIZATION,$swiss_confederation_tt$,X #L Швейцарської Конфедерації#!#!"\n',
        1818: ' sc_unification: "$SWI_ADJ$е об\'єднання"\n',
        1819: ' sc_unification_desc: "#L [ShowCultureGroupName(\'swiss_group\')]і#! землі були роздроблені занадто довго. Якщо мешканці Альп хочуть процвітання та безпеки, їм потрібно об\'єднатися під спільним знаменом."\n',
        1820: ' sc_unification_movement_event_happened_tt: "Відбулася [Concept(\'event\',\'подія\')|e] #Y «$flavor_swi.999.title$»#!. Для її спрацювання потрібні такі умови:\\n\\n[ShowTriggerConditions(\'flavor_swi_999_trigger\',PlayerScope.Self)]"\n',
        1821: ' sc_unification_same_religion_tt: "Кожен учасник сповідує або [ShowReligionName(\'catholic\')|l], або [ShowReligionName(\'lutheran\')|l], або [ShowReligionName(\'calvinist\')|l]"\n',
        1822: ' sc_found_swiss_republic: "$SWI_ADJ$а $republic$"\n',
        1823: ' sc_found_swiss_republic_desc: "Принципи і методи #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарської конфедерації#!#! добре сприймаються кожним кантоном, оскільки всі вони прагнуть до того, щоб їхній голос був врахований. Тим не менш децентралізованість конфедерації завжди ставитиме під загрозу безпеку і захищеність #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарського#!#! народу. Настав час об\'єднати конфедерацію в одну державу, а #TOOLTIP:GOVTYPE,republic,X #L республіка#!#! при цьому має зберегтися."\n',
        1824: ' sc_found_swiss_republic_specific_tt: "Влада #ONCLICK:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')] #TOOLTIP:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')],X [THIS.GetCountry.Custom(\'CL_RP\')|L]#!#! об\'єднує #ONCLICK:INTERNATIONAL_ORGANIZATION,swiss_confederation #TOOLTIP:INTERNATIONAL_ORGANIZATION,swiss_confederation,X #L Швейцарську Конфедерацію#!#!. У результаті формується #L [GetCountry(\'SWI\').GetAdjective|l]а#! #TOOLTIP:GOVTYPE,republic,X #L республіка#!#!"\n',
        1825: ' sc_found_swiss_republic_tt: "#TOOLTIP:INTERNATIONAL_ORGANIZATION,$swiss_confederation_tt$,X #L Швейцарська Конфедерація#!#! об\'єднується. У результаті формується #L [GetCountry(\'SWI\').GetAdjective]а#! #TOOLTIP:GOVTYPE,republic,X #L республіка#!#!"\n',
        1826: ' sc_found_swiss_monarchy: "$SWI_ADJ$а $monarchy$"\n',
        1827: ' sc_found_swiss_monarchy_desc: "Хоча спочатку #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарська конфедерація#!#! була республіканською унією, їй довелося зіткнутися з безліччю випробувань, протистояти яким було б набагато простіше під керівництвом єдиного сильного лідера. Світле майбутнє #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарського#!#! народу забезпечить тільки #TOOLTIP:GOVTYPE,monarchy,X #L монархія#!#!, яка має прийти на зміну конфедерації."\n',
        1828: ' sc_found_swiss_monarchy_specific_tt: "Влада #ONCLICK:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')] #TOOLTIP:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')],X [THIS.GetCountry.Custom(\'CL_RP\')|L]#!#! об\'єднує #ONCLICK:INTERNATIONAL_ORGANIZATION,swiss_confederation #TOOLTIP:INTERNATIONAL_ORGANIZATION,swiss_confederation,X #L Швейцарську Конфедерацію#!#!. У результаті формується #L [GetCountry(\'SWI\').GetAdjective|l]а#! #TOOLTIP:GOVTYPE,monarchy,X #L монархія#!#!"\n',
        1829: ' sc_found_swiss_monarchy_tt: "#TOOLTIP:INTERNATIONAL_ORGANIZATION,$swiss_confederation_tt$,X #L Швейцарська Конфедерація#!#! об\'єднується. У результаті формується #L [GetCountry(\'SWI\').GetAdjective|l]а#! #TOOLTIP:GOVTYPE,monarchy,X #L монархія#!#!"\n',
        1830: ' sc_found_swiss_theocracy: "$SWI_ADJ$а $theocracy$"\n',
        1831: ' sc_found_swiss_theocracy_desc: "#TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,swiss_confederation,X #L Швейцарська конфедерація#!#! зобов\'язана своїм нинішнім становищем не вільній волі республіканських голосів або авторитарній владі монархії, а лише божественному провидінню. Тільки #TOOLTIP:GOVTYPE,theocracy,X #L теократія#!#! дозволить #TOOLTIP:CULTUREGROUP,swiss_group,X #L швейцарському#!#! народу процвітати в цьому світі."\n',
        1832: ' sc_found_swiss_theocracy_specific_tt: "Влада #ONCLICK:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')] #TOOLTIP:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')],X [THIS.GetCountry.Custom(\'CL_RP\')|L]#!#! об\'єднує #ONCLICK:INTERNATIONAL_ORGANIZATION,swiss_confederation #TOOLTIP:INTERNATIONAL_ORGANIZATION,swiss_confederation,X #L Швейцарську Конфедерацію#!#!. У результаті формується #L [GetCountry(\'SWI\').GetAdjective|l]а#! #TOOLTIP:GOVTYPE,theocracy,X #L теократія#!#!"\n',
        1833: ' sc_found_swiss_theocracy_tt: "#TOOLTIP:INTERNATIONAL_ORGANIZATION,$swiss_confederation_tt$,X #L Швейцарська Конфедерація#!#! об\'єднується. У результаті формується #L [GetCountry(\'SWI\').GetAdjective|l]а#! #TOOLTIP:GOVTYPE,theocracy,X #L теократія#!#!"\n',
        1835: ' colonial_federation_unification: "Об\'єднання колоніальної федерації"\n',
        1836: ' colonial_federation_unification_desc: "Наші узи кувалися в полум\'ї боротьби за незалежність. Час замислитися про об\'єднання земель союзників у повноцінну державу."\n',
        1837: ' colonial_federation_found_republic: "Заснувати нову республіку"\n',
        1838: ' colonial_federation_found_republic_desc: "Тільки #TOOLTIP:GOVTYPE,republic,X #L республіканські#!#! принципи і процедури забезпечать права і свободи держав-учасниць і всіх підданих нашої держави."\n',
        1839: ' colonial_federation_found_republic_specific_tt: "Влада #ONCLICK:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')] #TOOLTIP:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')],X [THIS.GetCountry.Custom(\'CL_GEN\')|L]#!#! об\'єднує #ONCLICK:INTERNATIONAL_ORGANIZATION,swiss_confederation #TOOLTIP:INTERNATIONAL_ORGANIZATION,swiss_confederation,X #L Швейцарську Конфедерацію#!#!. У результаті формується #L [GetCountry(\'SWI\').GetAdjective|l]а#! #TOOLTIP:GOVTYPE,republic,X #L республіка#!#!"\n',
        1840: ' colonial_federation_found_republic_tt: "#TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,colonial_federation,X #L Колоніальна федерація#!#! перетворюється на єдину #TOOLTIP:GOVTYPE,republic,X #L республіку#!#!"\n',
        1841: ' colonial_federation_found_monarchy: "Заснувати нову монархію"\n',
        1842: ' colonial_federation_found_monarchy_desc: "Лише нова, справедлива #TOOLTIP:GOVTYPE,monarchy,X #L монархія#!#! забезпечить процвітання країнам-учасницям."\n',
        1843: ' colonial_federation_found_monarchy_specific_tt: "Під владою #ONCLICK:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')] #TOOLTIP:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')],X [THIS.GetCountry.Custom(\'CL_GEN\')|L]#!#! наша #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,colonial_federation,X #L колоніальна федерація#!#! перетвориться на єдину #TOOLTIP:GOVTYPE,monarchy,X #L монархію#!#!"\n',
        1844: ' colonial_federation_found_monarchy_tt: "#TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,colonial_federation,X #L Колоніальна федерація#!#! перетворюється на єдину #TOOLTIP:GOVTYPE,monarchy,X #L монархію#!#!"\n',
        1845: ' colonial_federation_found_theocracy: "Заснувати нову теократію"\n',
        1846: ' colonial_federation_found_theocracy_desc: "Наша #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,colonial_federation,X #L колоніальна федерація#!#! зобов\'язана своєю незалежністю не вільній волі республіканських голосів або авторитарній владі монархії, а лише божественному провидінню. Тільки #TOOLTIP:GOVTYPE,theocracy,X #L теократія#!#! дозволить нашому народу процвітати в цьому світі."\n',
        1847: ' colonial_federation_found_theocracy_specific_tt: "Під владою #ONCLICK:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')] #TOOLTIP:COUNTRY,[THIS.GetCountry.Custom(\'CL_tt\')],X [THIS.GetCountry.Custom(\'CL_GEN\')|L]#!#! #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,colonial_federation,X #L колоніальна федерація#!#! перетвориться на єдину #TOOLTIP:GOVTYPE,theocracy,X #L теократію#!#!"\n',
        1848: ' colonial_federation_found_theocracy_tt: "#TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,colonial_federation,X #L Колоніальна федерація#!#! перетворюється на єдину #TOOLTIP:GOVTYPE,theocracy,X #L теократію#!#!"\n',
        1849: ' AVERAGE_GREAT_POWER_SCORE_OF_IO: "Середній [Concept(\'great_power_score\',\'рахунок великої держави\')|e] [Concept(\'international_organization\',\'міжнародного об\'єднання\')|e]"\n',
        1850: ' AVERAGE_MILITARY_STRENGTH_OF_IO: "Середня [Concept(\'military_strength\', \'військова чисельність\')|e] [Concept(\'international_organization\',\'міжнародного об\'єднання\')|e]"\n',
        1851: ' mutual_defense_law: "Взаємний захист"\n',
        1852: ' mutual_defense_law_desc: "Політика, що описує, як учасники захищатимуть один одного у разі оголошення їм війни."\n',
        1853: ' assured_defense_policy: "Гарантований захист"\n',
        1854: ' assured_defense_policy_desc: "Учасники автоматично вступають в оборонні війни, оголошені іншим учасникам."\n',
        1855: ' automatic_defense_policy: "Автоматичний захист"\n',
        1856: ' automatic_defense_policy_desc: "Учасників автоматично закликають вступити в оборонні війни, оголошені іншим учасникам, але вони не зобов\'язані відгукнутися на заклик."\n',
        1857: ' possible_defense_policy: "Можливий захист"\n',
        1858: ' possible_defense_policy_desc: "Учасників можуть закликати вступити в оборонні війни, оголошені іншим учасникам, але вони не зобов\'язані відгукнутися на заклик."\n',
        1859: ' no_defense_policy: "Без захисту"\n',
        1860: ' no_defense_policy_desc: "Учасників не можуть закликати вступити в оборонні війни, оголошені іншим учасникам."\n',
        1861: ' mutual_offense_law: "Взаємний напад"\n',
        1862: ' mutual_offense_law_desc: "Політика, що описує, як учасники підтримуватимуть один одного у разі оголошення ними війни іншій державі."\n',
        1863: ' assured_offense_policy: "Гарантований напад"\n',
        1864: ' assured_offense_policy_desc: "Учасники автоматично приєднуються до наступальних воєн, оголошених іншими учасниками."\n',
        1865: ' automatic_offense_policy: "Автоматичний напад"\n',
        1866: ' automatic_offense_policy_desc: "Учасників автоматично закликають вступити в наступальні війни, оголошені іншими учасниками, але вони не зобов\'язані відгукнутися на заклик."\n',
        1867: ' possible_offense_policy: "Можливий напад"\n',
        1868: ' possible_offense_policy_desc: "Учасників можуть закликати вступити в наступальні війни, оголошені іншими учасниками, але вони не зобов\'язані відгукнутися на заклик."\n',
        1869: ' no_offense_policy: "Без нападу"\n',
        1870: ' no_offense_policy_desc: "Учасників не можуть закликати приєднатися до наступальних воєн, оголошених іншими учасниками."\n',
        1871: ' lordship_of_ireland_rule_law: "Влада в Ірландії"\n',
        1872: ' lordship_of_ireland_rule_law_desc: "Правити Ірландією — завдання не з легких. Її політичний ландшафт водночас нагадує хвилі бурхливого Атлантичного океану, що розбиваються об скелясті урвища, і стоячу болотну воду."\n',
        1873: ' lordship_of_ireland_rule_laudabiliter_policy: "Laudabiliter"\n',
        1874: ' lordship_of_ireland_rule_laudabiliter_policy_desc: "Колись Ірландію захопили англо-нормандські лицарі, жадібні слави і земель. Проте зараз королівська влада слабка."\n',
        1875: ' lordship_of_ireland_rule_laudabiliter_policy_tt: ""\n',
        1876: ' lordship_of_ireland_rule_statutes_of_kilkenny_policy: "Кілкенійський статут"\n',
        1877: ' lordship_of_ireland_rule_statutes_of_kilkenny_policy_desc: "Згідно з цим статутом англійські закони поширюються на всі ірландські графства. Він забороняє носіння кельтського одягу і змішані шлюби заради збереження самобутньої культури поселенців і їхньої переваги."\n',
        1878: ' lordship_of_ireland_rule_statutes_of_kilkenny_policy_tt: ""\n',
        1879: ' lordship_of_ireland_rule_ascendancy_policy: "Релігійний вплив"\n',
        1880: ' lordship_of_ireland_rule_ascendancy_policy_desc: "Ми можемо насильно навертати учасників манору в нашу віру."\n',
        1881: ' lordship_of_ireland_rule_ascendancy_policy_tt: ""\n',
        1883: ' UNION_TREASURY_COST: "Витрати скарбниці унії"\n',
        1884: ' union_foundation_law: "Створення унії"\n',
        1885: ' union_foundation_law_desc: "Закони #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#!, які визначають її характер і форму правління, централізовану або федеративну — якщо унія витримає перевірку часом."\n',
        1886: ' union_establish_seniority_policy: "Визначення старшинства"\n',
        1887: ' union_establish_seniority_policy_desc: "[GetInternationalOrganizationType(\'union\').GetName] може керуватися лише одним з тронів. Призначення старшого партнера унії визначає, чий трон представлятиме всю унію загалом."\n',
        1888: ' union_maintain_federal_status_policy: "Збереження федерального статусу"\n',
        1889: ' union_maintain_federal_status_policy_desc: "Суверенітет держав, що входять до #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#!, священний і не підлягає обговоренню. Навіть якщо над ними царює один володар, він не має права змінювати традиційні порядки держав-учасниць."\n',
        1890: ' union_senior_partner_policy_at: "Доступний особливий статус [#TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старшого#!#!\')]і #TOOLTIP:SPECIAL_STATUS,junior_partner,X #L молодшого#!#! партнерів"\n',
        1891: ' union_senior_partner_policy_tt: "[ROOT.GetInternationalOrganization.GetCountryWithHighestGreatPower.GetName] стан[ROOT.GetInternationalOrganization.GetCountryWithHighestGreatPower.Custom(\'end_ityat\')]е #TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старшим партнером#!#! (держава має найвищий [Concept(\'great_power_score\', \'рахунок великої держави\')|e] в [Concept(\'union\', \'унії\')|e])"\n',
        1892: ' union_senior_partner_policy_specific_tt: "[ROOT.GetInternationalOrganization.MakeScope.GetVariable(\'pre_selected_senior_partner\').GetCountry.GetName] стан[ROOT.GetInternationalOrganization.MakeScope.GetVariable(\'pre_selected_senior_partner\').GetCountry.Custom(\'end_ityat\')]е #TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старшим партнером#!#!"\n',
        1893: ' union_unlocks_independence_casus_belli_tt: "Відкриває [Concept(\'casus_belli\', \'привід для війни\')|e] #TOOLTIP:CASUS_BELLI,cb_union_independence,X #L «Незалежність унії»#!#! для кожного молодшого партнера, який #Y слабший#!, ніж #TOOLTIP:SPECIAL_STATUS,senior_partner_tt,X #L старший партнер#!#!"\n',
        1894: ' union_unlocks_war_for_seniority_casus_belli_tt: "Відкриває [Concept(\'casus_belli\', \'привід для війни\')|e] #TOOLTIP:CASUS_BELLI,cb_union_war_for_seniority,X #L «Війна за старшинство»#!#! для кожного молодшого партнера, який #Y не слабший#!, ніж #TOOLTIP:SPECIAL_STATUS,senior_partner_tt,X #L старший партнер#!#!"\n',
        1895: ' union_codified_inheritance_law: "Систематизована спадщина"\n',
        1896: ' union_codified_inheritance_law_desc: "Для стабільності #ONCLICK:INTERNATIONAL_ORGANIZATION,union #TOOLTIP:INTERNATIONAL_ORGANIZATION,union,X #L унії#!#! правила спадкування для кожного її учасника мають бути систематизовані таким чином, щоб кожна держава мала однаковий порядок престолонаслідування."\n',
        1897: ' union_senior_succession_law: "Єдині правила престолонаслідування"\n',
        1898: ' union_senior_succession_law_desc: "Порядок престолонаслідування в #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#! визначається законом, якого дотримується #TOOLTIP:SPECIAL_STATUS,senior_partner_tt,X #L старший партнер#!#!. Інші держави-учасниці мають по можливості дотримуватися цього закону."\n',
        1899: ' union_sovereign_succession_law: "Місцеві правила престолонаслідування"\n',
        1900: ' union_sovereign_succession_law_desc: "Жодна держава, що входить до #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#!, не має права диктувати свої закони про престолонаслідування іншим країнам. Порядок престолонаслідування — внутрішня справа кожного учасника унії."\n',
        1901: ' union_codified_inheritance_policy_at: "Кожен учасник #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#! по можливості приймає [Concept(\'heir_selection\', \'правило престолонаслідування\')|e], якого дотримується #TOOLTIP:SPECIAL_STATUS,senior_partner_tt,X #L старший партнер#!#!"\n',
        1902: ' union_codified_inheritance_policy_bt: "#R Заблоковані [Concept(\'heir_selections\', \'правила престолонаслідування\')|e] не можна застосувати або скасувати#!"\n',
        1903: ' union_economic_law: "Економіка унії"\n',
        1904: ' union_economic_law_desc: "Навіть якщо монарх займає кілька престолів, економіка підвладних йому держав може бути розрізнена. Цей закон сприяє зближенню держав-учасниць #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#!."\n',
        1905: ' union_unified_treasury_policy: "Спільна скарбниця"\n',
        1906: ' union_unified_treasury_policy_desc: "Державна скарбниця держав, що входять до #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#!, об\'єднується в єдину інституцію, яка поповнюватиме скарбницю монарха, дозволяючи йому витрачати золото в інтересах всієї унії."\n',
        1907: ' union_cooperative_investment_policy: "Спільне фінансування"\n',
        1908: ' union_cooperative_investment_policy_desc: "Скарбниця держав, що входять до #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#!, не належить нікому конкретно. Королівський двір розпоряджається цими коштами, щоб удосконалювати інфраструктуру всіх держав-учасниць."\n',
        1909: ' union_diplomatic_law: "Принципи дипломатії"\n',
        1910: ' union_diplomatic_law_desc: "З огляду на те, що #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унією#!#! править один монарх, важливо визначити, як саме ведеться дипломатична політика держав-учасниць."\n',
        1911: ' union_unified_external_diplomacy_policy: "Єдина зовнішня політика"\n',
        1912: ' union_unified_external_diplomacy_policy_desc: "Дипломатичну політику #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#! визначає #TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старший партнер#!#!. Інші держави-учасниці не мають власної зовнішньої політики."\n',
        1913: ' union_organized_diplomats_policy: "Дипломати унії"\n',
        1914: ' union_organized_diplomats_policy_desc: "Посланці #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#! служать не конкретній державі, а унії загалом. Кожна держава-учасниця може користуватися їхніми послугами в інтересах своєї зовнішньої політики."\n',
        1915: ' union_legislature_law: "Законодавство унії"\n',
        1916: ' union_legislature_law_desc: "Управління #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унією#!#! потребує уніфікованих правил. Тільки єдине законодавство може забезпечити довгострокове функціонування унії."\n',
        1917: ' union_aligned_legislature_policy: "Узгоджене законодавство"\n',
        1918: ' union_aligned_legislature_policy_desc: "Для забезпечення єдиноманітності і уніфікації всі закони і політики учасників #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#! приводяться у відповідність із законодавством #TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старшого партнера#!#!."\n',
        1919: ' union_aligned_legislature_policy_at: "Кожен учасник #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#! по можливості приймає [Concept(\'government_reforms\', \'державні принципи\')|e] і [Concept(\'policies\', \'політики\')|e], яких дотримується #TOOLTIP:SPECIAL_STATUS,senior_partner_tt,X #L старший партнер#!#!"\n',
        1920: ' union_federal_legislature_policy: "Місцеве законодавство"\n',
        1921: ' union_federal_legislature_policy_desc: "Різноманітність законів і звичаїв — це зовсім не недолік #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#!, а її основна перевага. Внутрішня політика має залишатися приватною справою кожної з держав-учасниць."\n',
        1922: ' union_mutual_offense_law: "Взаємний напад"\n',
        1923: ' union_mutual_offense_law_desc: "[GetInternationalOrganizationType(\'union\').GetName] — це насамперед оборонний союз, проте у разі військових конфліктів учасники можуть допомагати один одному, якщо висловлять згоду на подібні дії."\n',
        1924: ' union_assured_offense_policy: "Гарантований напад"\n',
        1925: ' union_assured_offense_policy_desc: "#TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L Унія#!#! виступає як агресивний союз. Вороги здригнуться, коли наші солдати єдиним фронтом виступлять проти них."\n',
        1926: ' union_automatic_offense_policy: "Обов\'язковий напад"\n',
        1927: ' union_automatic_offense_policy_desc: "#TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L Унія#!#! віддає перевагу агресивній зовнішній політиці. Підтримка товаришів по унії в наступальних війнах заохочується."\n',
        1928: ' union_possible_offense_policy: "Можливий напад"\n',
        1929: ' union_possible_offense_policy_desc: "[GetInternationalOrganizationType(\'union\').GetName] має завойовувати нові землі і підвищувати свою міць, щоб вижити. У разі війни кожен учасник має право закликати на допомогу інших учасників."\n',
        1930: ' union_unification_of_crowns_law: "Перспектива об\'єднання"\n',
        1931: ' union_unification_of_crowns_law_desc: "У більшості випадків #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унія#!#! — не більше ніж пухка конфедерація різних держав, волею випадку опинившихся під владою спільного монарха. Проте можливість їхнього остаточного об\'єднання під прапором #TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старшого партнера#!#! теж не варто виключати…"\n',
        1932: ' union_rapid_crown_unification_policy: "Стрімке об\'єднання корон"\n',
        1933: ' union_rapid_crown_unification_policy_desc: "Подальше підвищення ефективності чиновницького апарату #TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старшого партнера#!#! прискорює процес приєднання #TOOLTIP:SPECIAL_STATUS,junior_partner,X #L молодшого партнера#!#!."\n',
        1934: ' union_swift_crown_unification_policy: "Швидке об\'єднання корон"\n',
        1935: ' union_swift_crown_unification_policy_desc: "Дипломатичний і адміністративний апарати #TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старшого партнера#!#! значно вдосконалилися, що дозволить швидше інтегрувати держави-учасниці."\n',
        1936: ' union_crown_unification_policy: "Об\'єднання корон"\n',
        1937: ' union_crown_unification_policy_desc: "Настав підходящий час для повної централізації #TOOLTIP:INTERNATIONAL_ORGANIZATION_TYPE,union,X #L унії#!#!. Усі держави-учасниці висловлюють свою згоду на дипломатичне приєднання до #TOOLTIP:SPECIAL_STATUS,senior_partner,X #L старшого партнера#!#!."\n',
        1938: ' union_federal_union_policy: "Федеративна унія"\n',
        1939: ' union_federal_union_policy_desc: "[GetInternationalOrganizationType(\'union\').GetName] — це насамперед оборонний союз. Ніхто з учасників не зацікавлений у тому, щоб об\'єднати корони в єдину державу, і суверенітет усіх держав-учасниць має залишатися непорушним."\n',
        1941: ' dop_rudolfine_house_rules: "Реформовані правила династії"\n',
        1942: ' dop_rudolfine_house_rules_desc: "Реформовані правила династії — це система спільного управління австрійськими землями, яка являє рівний статус усім чоловікам у родині, але при цьому старший має особливі привілеї."\n',
        1944: ' foreign_court_customs_policy: "Чужинецькі звичаї"\n',
        1945: ' foreign_court_customs_policy_desc: "Обмеженість до добра не доведе. Ми можемо збагатити свою культуру, почерпнувши натхнення в чужинецьких дворів."\n',
        1947: ' colonial_representation_law: "Колоніальне представництво"\n',
        1948: ' colonial_representation_law_desc: "Наш вплив на підвладні нам території залежить від примх нашого сюзерена."\n',
        1949: ' colonial_representation_law_no: "Відсутність представництва"\n',
        1950: ' colonial_representation_law_no_desc: "Ми не маємо права брати участь у засіданнях парламенту, а наш сюзерен справляє суттєвий вплив на економіку."\n',
        1951: ' colonial_representation_law_yes: "Представництво в парламенті"\n',
        1952: ' colonial_representation_law_yes_desc: "Ми отримали право голосу в прийнятті парламентських рішень нашої держави, при цьому вплив нашого сюзерена був обмежений."\n',
        1954: ' mongol_law_policy: "Монгольське право"\n',
        1955: ' mongol_law_policy_desc: "Населенню нічого не відомо про монгольське право, але саме воно забезпечує досягнення трьох важливих цілей: об\'єднання народу, покора правителю і сувора кара за злочини проти держави. Зберігаючи це право в таємниці, ми можемо легко змінювати його, підлаштовуючи під поточні потреби держави."\n',
        1957: ' dahsala_system: "Система дахсала"\n',
        1958: ' dahsala_system_desc: "Поточна система оподаткування занадто хаотична: через місцевих порядків індійські простолюдини платять різні податки залежно від регіону, де вони проживають. Впровадивши систему дахсали, ми зможемо збирати податки більш організовано."\n',
        1959: ' zabiti: "Система забті"\n',
        1960: ' zabiti_desc: "Система, при якій податок залежить від розміру землі і її вартості. Власники землі мають виплачувати його або сріблом, або врожаєм. При цьому, якщо їхня земля довгий час не оброблялася, вони звільняються від податку доти, доки вона знову не почне приносити врожай."\n',
        1961: ' ghalla_bakshi: "Система гхалла бакші"\n',
        1962: ' ghalla_bakshi_desc: "Простий люд підтримує цю форму оподаткування, оскільки вона дозволяє виплачувати потрібну суму врожаєм, а не грішми."\n',
        1963: ' nasaq: "Система насак"\n',
        1964: ' nasaq_desc: "З трьох систем ця — найнечесніша. Сума податку залежить від середнього попиту на землю за останні десятиліття."\n',
        1965: ' mansabdar_system: "Мансабдари"\n',
        1966: ' mansabdar_system_desc: "Замість того, щоб покладатися на феодальну аристократію, ми могли б надати можливість займати будь-яку армійську посаду всім, хто доведе, що здатний на це."\n',
        1968: ' hab_military_frontier: "Військові на прикордонній смузі"\n',
        1969: ' hab_military_frontier_desc: "Тепер наш кордон охороняють військові. Вони мають захистити нашу державу від вторгнення армій язичників."\n',
        1970: ' frontier_maintained: "Кордон захищений"\n',
        1971: ' frontier_maintained_desc: "Кордон чудово охороняється: наші солдати готові захищати державу від ворожих загарбників."\n',
        1972: ' frontier_not_maintained: "Кордон не захищений"\n',
        1973: ' frontier_not_maintained_desc: "Наш кордон не охороняється через проблем з фінансуванням. У разі вторгнення ворог без труднощів перейде його."\n',
        1975: ' vedic_education: "Ведична освіта"\n',
        1976: ' vedic_education_desc: "Система освіти, при якій люди можуть разом навчатися #TOOLTIP:RELIGION,$hindu_tt$,X #L індуїстським#!#! практикам без поділу на касти."\n',
        1978: ' guru_nanak_guruship: "Вчення гуру Нанака"\n',
        1979: ' guru_nanak_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_nanak\').GetName]."\n',
        1980: ' vand_chhako: "Ванд чхако"\n',
        1981: ' vand_chhako_desc: "Один з основних принципів вчення, яке розробив [GetCharacter(\'guru_nanak\').GetName]. Він проголошує, що сикхи мають ділитися своїм майном зі спільнотою."\n',
        1982: ' kirat_karo: "Кірат каро"\n',
        1983: ' kirat_karo_desc: "Один з основних принципів вчення, яке розробив [GetCharacter(\'guru_nanak\').GetName]. Він проголошує, що сикхи мають старанно трудитися, використовуючи таланти і навички, даровані їм Богом."\n',
        1984: ' naam_japo: "Нам джапо"\n',
        1985: ' naam_japo_desc: "Один з основних принципів вчення, яке розробив [GetCharacter(\'guru_nanak\').GetName]. Він проголошує, що сикхи мають медитувати і повторювати мантри з ім\'ям Бога, щоб здобути з ним духовний зв\'язок.ੴ"\n',
        1986: ' guru_angad_guruship: "Вчення гуру Ангада"\n',
        1987: ' guru_angad_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_angad\').GetName]."\n',
        1988: ' gurmukhi_script: "Писемність гурмукхі"\n',
        1989: ' gurmukhi_script_desc: "Ця писемність, яку винайшов [GetCharacter(\'guru_angad\').GetName], використовуватиметься для написання різних священних текстів #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхізму#!#!."\n',
        1990: ' langar_community: "Лангари"\n',
        1991: ' langar_community_desc: "Лангари — це їдальні при храмах, де годуватимуть безкоштовно всіх, незалежно від їхнього віросповідання, становища в суспільстві і національності."\n',
        1992: ' mall_akhara: "Малл Акхара"\n',
        1993: ' mall_akhara_desc: "Бійцівські арени для тренувань. Тут можна буде не лише зміцнити тіло, але й відточити свої бойові навички."\n',
        1994: ' guru_amar_das_guruship: "Вчення гуру Амар Даса"\n',
        1995: ' guru_amar_das_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_amar_das\').GetName]."\n',
        1996: ' dasvandh_tax: "Податок дасвандх"\n',
        1997: ' dasvandh_tax_desc: "Ця форма оподаткування передбачає виплату десятої частини доходу на користь гуру, який надалі може використовувати ці гроші для потреб спільноти."\n',
        1998: ' ananda_karaja: "Анада караджа"\n',
        1999: ' ananda_karaja_desc: "Це #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхська#!#! весільна церемонія, яку придумав [GetCharacter(\'guru_amar_das\').GetName]. Її назва означає «діяння в ім\'я щастя». Під час церемонії виконуються особливі релігійні гімни, спрямовані на досягнення духовної рівноваги і зв\'язку з божественним."\n',
        2000: ' sangat_equality: "Рівність у громаді Сангат"\n',
        2001: ' sangat_equality_desc: "Чоловіки і жінки рівні перед Богом, тому і ті, і інші мають право бути частиною чернечої громади Сангат і навіть очолювати її."\n',
        2002: ' guru_ram_das_guruship: "Вчення гуру Рам Даса"\n',
        2003: ' guru_ram_das_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_ram_das\').GetName]."\n',
        2004: ' urbanization_projects: "Проекти міського розвитку"\n',
        2005: ' urbanization_projects_desc: "Маючи наполегливість і працюючи спільно, можна побудувати найвеличніше місто, яке багато століть служитиме для #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхів#!#! священним місцем."\n',
        2006: ' scripture_hymns: "Священні гімни"\n',
        2007: ' scripture_hymns_desc: "Писання — головна книга віруючих. Ми маємо увічнити божественну мудрість у прекрасних гімнах."\n',
        2008: ' masand_system: "Система масанд"\n',
        2009: ' masand_system_desc: "Ця система передбачає відправлення місіонерів до різних областей з метою поширення #L [ShowReligionAdjective(\'sikhism\')|l]ого#! вчення і збору податків на користь гуру."\n',
        2010: ' guru_arjan_guruship: "Вчення гуру Арджана"\n',
        2011: ' guru_arjan_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_arjan\').GetName]."\n',
        2012: ' adi_granth: "Аді Грантх"\n',
        2013: ' adi_granth_desc: "Збірник гімнів, який склав [GetCharacter(\'guru_arjan\').GetName]. Він містить безліч гімнів минулих гуру, які послужать основою для наших священних писань."\n',
        2014: ' holy_abode: "Свята обитель"\n',
        2015: ' holy_abode_desc: "Якщо зберігати релігійні тексти в священних храмах, вони стануть священними місцями, до яких здійснюватимуть паломництва всі прихильники [ShowReligionAdjective(\'sikhism\')|l]ого#! вчення."\n',
        2016: ' martyrdom: "Мучеництво"\n',
        2017: ' martyrdom_desc: "Наша #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхська#!#! віра міцна, і ми не зречемося від неї навіть під загрозою катувань і смерті."\n',
        2018: ' guru_hargobind_guruship: "Вчення гуру Хар Гобінда"\n',
        2019: ' guru_hargobind_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_hargobind\').GetName]."\n',
        2020: ' akal_takht: "Акал Такхт"\n',
        2021: ' akal_takht_desc: "Назву цієї споруди можна перекласти як «Трон Вічного». Вона служитиме резиденцією #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхських#!#! лідерів і символом їхньої влади."\n',
        2022: ' protection_of_the_poor: "Захист бідняків"\n',
        2023: ' protection_of_the_poor_desc: "Наша армія не має бути інструментом пригноблення і тиранії. Її завдання — захищати від самодурів найуразливіші верстви населення."\n',
        2024: ' miri_piri: "Мірі пірі"\n',
        2025: ' miri_piri_desc: "#TOOLTIP:RELIGION,$sikhism_tt$,X #L Сикхізм#!#! зможе розквітнути в повній мірі лише тоді, коли гуру об\'єднають у своїх руках і духовну, і світську владу."\n',
        2026: ' guru_har_rai_guruship: "Вчення гуру Хар Рая"\n',
        2027: ' guru_har_rai_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_har_rai\').GetName]."\n',
        2028: ' impartial_manji_heads: "Непідкупні голови манджі"\n',
        2029: ' impartial_manji_heads_desc: "Ті, хто стоїть на чолі духовної ієрархії, мають відкинути упередженість і сумлінно служити інтересам #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхів#!#!."\n',
        2030: ' fragance_of_a_flower: "Аромат квітки"\n',
        2031: ' fragance_of_a_flower_desc: "Якщо зірвати квітку однією рукою, а подарувати — іншою, обидві руки пахнутимуть однаково. Яке б вчення ми не сповідували, божественна длань торкається всіх нас."\n',
        2032: ' nature_guardian: "Турбота про природу"\n',
        2033: ' nature_guardian_desc: "Ми маємо жити в гармонії з природою, а не ставити її на службу людству. Захищайте її і дбайте про неї так само, як вона дбає про вас."\n',
        2034: ' guru_har_krishan_guruship: "Вчення гуру Хар Крішана"\n',
        2035: ' guru_har_krishan_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_har_krishan\').GetName]."\n',
        2036: ' treat_the_sick: "Лікування хворих"\n',
        2037: ' treat_the_sick_desc: "Хвороби і епідемії — прокляття людства. Ми старанно лікуватимемо всіх хворих, щоб наше суспільство залишалося здоровим."\n',
        2038: ' unexpected_knowledge: "Неоднозначна природа знання"\n',
        2039: ' unexpected_knowledge_desc: "Духовна сила гуру незаперечна, оскільки їм відомі такі істини, які неможливо осягнути звичайним способом. Разом з тим, ці мудрі наставники можуть вільно спілкуватися на богословські теми з будь-ким, навіть неграмотними людьми."\n',
        2040: ' young_humility: "Юні уми"\n',
        2041: ' young_humility_desc: "Ніхто не знає всіх відповідей. Завжди знайдуться сфери, недоступні нашому розумінню, і люди, які пізнали приховану від нас істину. Часом дитина може бути в чомусь розумнішою за дорослого. У цьому світі ми всі немовлята."\n',
        2042: ' guru_tegh_bahadur_guruship: "Вчення гуру Тегх Бахадура"\n',
        2043: ' guru_tegh_bahadur_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_tegh_bahadur\').GetName]."\n',
        2044: ' word_of_a_sikh: "Слово сикха"\n',
        2045: ' word_of_a_sikh_desc: "#TOOLTIP:RELIGION,$sikhism_tt$,X #L Сикхи#!#! переконані, що Бог всюдисущий, а отже, кожне слово вимовляється в його присутності. Саме тому вони не мають права порушувати свої клятви."\n',
        2046: ' guru_travels: "Подорожі гуру"\n',
        2047: ' guru_travels_desc: "Залишаючись в одному і тому самому місці, гуру просто не зможе поширювати вчення #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхізму#!#!. Отже, він має багато подорожувати і спілкуватися з представниками інших народів і віросповідань."\n',
        2048: ' resist_persecution: "Жодних переслідувань"\n',
        2049: ' resist_persecution_desc: "Вороги істинного вчення завжди переслідуватимуть віруючих, але наші переконання міцні, і ніхто не зможе похитнути їх."\n',
        2050: ' guru_gobind_singh_guruship: "Вчення гуру Гобінда Сінгха"\n',
        2051: ' guru_gobind_singh_guruship_desc: "Набір практик і настанов, які створив [GetCharacter(\'guru_gobind_singh\').GetName]."\n',
        2052: ' sikh_pluralism: "Різнорідність сикхізму"\n',
        2053: ' sikh_pluralism_desc: "Представники громади [ShowLawName(\'khalsa_law\')|l] — поборники #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхської#!#! віри, проте далеко не всі сикхи зараховують себе до цієї групи. Це доводить, що всередині нашої віри є безліч течій, і ця різноманітність робить нас сильнішими."\n',
        2054: ' dharamyudh: "Дхарам\'юдх"\n',
        2055: ' dharamyudh_desc: "Дхарам\'юдх, що означає «війна за справедливість», покликана захищати #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхську#!#! віру і її послідовників. До неї можна вдаватися лише в крайньому випадку, коли інші методи вже вичерпані. Тим не менш кожен сикх має бути готовий узятися за зброю і дати відсіч гнобителям."\n',
        2056: ' dasam_granth: "Дасам Грантх"\n',
        2057: ' dasam_granth_desc: "Збірник гімнів і віршів, які написав [GetCharacter(\'guru_gobind_singh\').GetName]. За своєю важливістю цей твір не поступається «Аді Грантх», тому в храмах вони часто зберігаються поруч."\n',
        2058: ' khalsa_law: "Хальса"\n',
        2059: ' khalsa_law_desc: "Громада воїнів, які поклялися захищати #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхську#!#! віру і її послідовників. Їхні обряди посвячення і норми поведінки — приклад праведності і самовідданості для всіх віруючих."\n',
        2060: ' guru_panth: "Гуру Пантх"\n',
        2061: ' guru_panth_desc: "Духовними лідерами #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхізму#!#! мають бути всі представники громади [ShowLawName(\'khalsa_law\')|l]. Таким чином вони разом становитимуть єдиного гуру."\n',
        2062: ' khalsa_fauj: "Хальса Фаудж"\n',
        2063: ' khalsa_fauj_desc: "[ShowLawName(\'khalsa_law\')] має організувати власну повноцінну армію. Тільки так її представники зможуть стати захисниками #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхської#!#! віри."\n',
        2064: ' amrit_sanskar: "Амріт Санскар"\n',
        2065: ' amrit_sanskar_desc: "Представники громади [ShowLawName(\'khalsa_law\')|l] не якісь дикуни, бездумно рвучись у бій. Це найдостойніші люди, які проходять через обряди посвячення і дотримуються суворих правил поведінки, прийнятих у громаді. Престиж цих воїнів полягає зовсім не в силі, а в благочесті і духовній чистоті."\n',
        2066: ' guru_granth_sahib_guruship: "Вчення «Гуру Грантх Сахіб»"\n',
        2067: ' guru_granth_sahib_guruship_desc: "Набір практик і настанов, представлених у «[ShowWorkOfArtName(\'guru_granth_sahib\')]»."\n',
        2068: ' eternally_living_guru: "Вічний гуру"\n',
        2069: ' eternally_living_guru_desc: "«[ShowWorkOfArtName(\'guru_granth_sahib\')]» — священний текст, який шанується як останній з гуру. Він вічно служитиме путівною зіркою для всіх послідовників #TOOLTIP:RELIGION,$sikhism_tt$,X #L сикхізму#!#!."\n',
        2070: ' divine_justice: "Божественна справедливість"\n',
        2071: ' divine_justice_desc: "Вчення, викладене в «[ShowWorkOfArtName(\'guru_granth_sahib\')]», заповідує людям жити в мирі і гармонії, тобто відповідно до природних законів, встановлених справедливим Богом."\n',
        2072: ' unchanging_writing: "Незмінний текст"\n',
        2073: ' unchanging_writing_desc: "«[ShowWorkOfArtName(\'guru_granth_sahib\')]» складався різними гуру протягом кількох сотень років, і тепер нарешті досяг повної і вічної форми. З цього моменту жодна літера цього священного тексту не буде змінена."\n',
        2074: ' tur_kanum_i_osmani: "Османський закон"\n',
        2075: ' tur_kanum_i_osmani_desc: "Сукупність правил і покладень, що утворюють законодавство #ONCLICK:COUNTRY,[GetCountry(\'TUR\').Custom(\'CL_tt\')] #TOOLTIP:COUNTRY,[GetCountry(\'TUR\').Custom(\'CL_tt\')],X [GetCountry(\'TUR\').Custom(\'CL_GEN\')|L]#!#!. Його основне завдання — забезпечити внутрішню стабільність багатонаціональної держави, а не полегшити завоювання нових земель."\n',
        2076: ' tur_has_not_first_option_in_flavor_tur_208_event: "У [Concept(\'event\', \'події\')|e] #Y «$flavor_tur.208.title$»#! НЕ обрано перший варіант відповіді"\n',
        2077: ' tur_has_picked_first_option_in_flavor_tur_208_event: "У [Concept(\'event\', \'події\')|e] #Y «$flavor_tur.208.title$»#! обрано перший варіант відповіді"\n',
        2079: ' reformed_hussite_armies_policy: "Доопрацьована гуситська тактика"\n',
        2080: ' reformed_hussite_armies_policy_desc: "Наші предки були майстрами оборони. Довгі роки вони давали відсіч ворогам. Настав час перейти в наступ і продемонструвати сусідським єретикам і язичникам, на що здатна наша реформована і надзвичайно агресивна армія."\n',
        2081: ' ira_alcohol_ban: "Обмеження вживання алкоголю"\n',
        2082: ' ira_alcohol_ban_desc: "Щоб знайти золоту середину між релігійними обов\'язками служителів нашої віри і бажаннями населення, ми маємо вирішити, чи вводити обмеження на вживання спиртного."\n',
        2083: ' ban_on_alcohol: "Заборона алкоголю"\n',
        2084: ' ban_on_alcohol_desc: "Заборонивши всім громадянам держави вживати спиртне, ми отримаємо підтримку служителів нашої віри, але розгнівимо населення."\n',
        2085: ' no_restriction_on_alcohol: "Вільне вживання алкоголю"\n',
        2086: ' no_restriction_on_alcohol_desc: "Якщо ми не станемо забороняти алкоголь, а, навпаки, дозволимо всім громадянам його вживати, це забезпечить нам лояльність населення."\n',
        2088: ' act_of_navigation: "Навігаційний акт"\n',
        2089: ' act_of_navigation_desc: "Ми маємо оспорювати панування наших конкурентів на всіх ринках. За допомогою централізованих розпоряджень і торговельних привілеїв ми спробуємо домогтися переваги наших купців над купцями наших ворогів і суперників."\n',
        2090: ' lit_casimir_code_policy: "Судебник Великого князівства Литовського"\n',
        2091: ' lit_casimir_code_policy_desc: "$lit_casimir_code_policy$ покликаний вирішити проблему відсутності зводу законів і побороти злочинні дії осіб, наділених владою. З його допомогою [GetEstateName(\'crown_estate\')|l] зуміють приборкати хаос і отримають більше повноважень."\n',
    }

    with open(file_path, 'r', encoding='utf-8-sig') as f:
        lines = f.readlines()

    count = 0
    for line_num, new_content in m.items():
        if 0 <= line_num < len(lines):
            lines[line_num] = new_content
            count += 1

    with open(file_path, 'w', encoding='utf-8-sig') as f:
        f.writelines(lines)

    print(f"✓ Виправлено {count} рядків (1650-2091)")
    print(f"")
    print(f"🎉🎉🎉 ПОВНІСТЮ ЗАВЕРШЕНО переклад файлу laws_and_policies_l_english.yml! 🎉🎉🎉")
    print(f"Перекладено 2091 рядків з 2091 (100%)")

if __name__ == '__main__':
    apply()
