#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Переклад advances_l_english.yml: рядки 1600-1800
"""
import io

FILE_PATH = '/Users/furmonenko/Desktop/eu5-ukrainian-localization/main_menu/localization/english/advances_l_english.yml'

# Словник перекладів (номер рядка: переклад)
translations = {
    1600: ' conquistador_advance: "Конкістадори"\n',
    1601: ' conquistador_advance_desc: "У Новий Світ рвуться шукачі пригод усіх мастей, готові ризикнути грошима і життям заради баснословного багатства, слави і впливу. Експедиції з невизначеним результатом, що здійснюються за веління корони, офіційно називаються конкістою — завоюванням."\n',
    1602: ' grand_display_of_faith: "Грандіозна демонстрація віри"\n',
    1603: ' grand_display_of_faith_desc: "Потрібно зводити великі монументи на славу Господа. Так ми покажемо не лише силу своєї істинної віри, а й те, яких висот досягли наші архітектори."\n',
    1604: ' monastery_productions: "Чернеча ощадливість"\n',
    1605: ' monastery_productions_desc: "Мешканці наших монастирів дотримуються ідеалів економії і поміркованості. Іншим представникам духівництва варто брати з них приклад."\n',
    1606: ' reform_church_music: "Реформа церковної музики"\n',
    1607: ' reform_church_music_desc: "Нам слід прийняти запропоновану реформу літургічної музики. Невиразні мелодії, які зараз у ходу, повинні поступитися місцем новим."\n',
    1608: ' frequent_councils: "Збиратися частіше"\n',
    1609: ' frequent_councils_desc: "Слід частіше проводити релігійні зібрання, адже нас уже давно критикують за те, що ми рідко їх організовуємо. Хоча наш вплив на курію обмежений, ми володіємо достатньою владою, щоб втілити цю ідею в життя."\n',
    1610: ' mendicant_orders: "Жебрацькі ордени"\n',
    1611: ' mendicant_orders_desc: "Релігійні ордени, члени яких ведуть життя бідних мандрівників, приносять користь у найрізноманітніших куточках держави. Ми повинні підтримати цих людей, не порушуючи їхніх обітів."\n',
    1612: ' exsurge_domine: "Повстань, Господи!"\n',
    1613: ' exsurge_domine_desc: "Сам Господь повстане і вирве зло з коренем, позбавивши наші землі від єретиків!"\n',
    1614: ' confutatio_augustana: "Боротьба з хибними віруваннями"\n',
    1615: ' confutatio_augustana_desc: "У такі неспокійні часи потрібно чітко пояснити нашим ленникам, що саме вважається єрессю і яких поглядів повинен дотримуватися благочестивий христянин."\n',
    1616: ' roman_catechism: "Римський катехізис"\n',
    1617: ' roman_catechism_desc: "Наше духівництво має слідувати приписам церкви. Це спростить навчання священників і підвищить ефективність їхнього служіння."\n',
    1618: ' oversea_missions: "Заморські місії"\n',
    1619: ' oversea_missions_desc: "Священники прагнуть нести нашу віру в заморські землі і достатньо підготовлені для цього завдання. Їхні зусилля спростять і здешевлять освоєння нових територій."\n',
    1620: ' baptism_books: "Книги про хрещення"\n',
    1621: ' baptism_books_desc: "Хрещення — один зі стовпів нашого вчення. Всі священнослужителі повинні мати можливість проводити це таїнство."\n',
    1622: ' second_scholasticism: "Друга схоластика"\n',
    1623: ' second_scholasticism_desc: "Нам варто відродити і вдосконалити схоластику — середньовічну релігійну філософію."\n',
    1626: ' index_librorum_prohibitorum: "Список заборонених книг"\n',
    1627: ' index_librorum_prohibitorum_desc: "Небезпечні ідеї Реформації можуть захопити уми наших підданих через книги, що пропагують цю єресь."\n',
    1628: ' catholic_cuius_regio_eius_religio: "Чия держава, того і віра"\n',
    1629: ' catholic_cuius_regio_eius_religio_desc: "#italic Чия країна, того й віра.#! Нам доведеться змиритися з тим, що релігійні погляди жителів інших країн відрізняються від наших, і часом це відіграватиме важливу роль у вирішенні дипломатичних питань."\n',
    1630: ' embellish_baroque_art: "Мистецтво бароко"\n',
    1631: ' embellish_baroque_art_desc: "Церква традиційно підтримувала мистецтво. Бароко повною мірою відображає наш релігійний світогляд, і ми повинні продовжувати покровительствувати творцям, що розвивають цей стиль."\n',
    1632: ' national_churches: "Національна церква"\n',
    1633: ' national_churches_desc: "Держава має посилити контроль над церквою. Не можна допустити зростання впливу іноземних структур на нашу адміністрацію."\n',
    1634: ' entrenched_church: "Укорінення церкви"\n',
    1635: ' entrenched_church_desc: "Неважливо, ким ми правимо: церква допоможе нам об\'єднати людей під своєю егідою."\n',
    1636: ' catholic_enlightenment: "Католицьке просвітництво"\n',
    1637: ' catholic_enlightenment_desc: "Щоб наша віра пережила епоху Просвітництва, треба адаптуватися і поглянути на церкву свіжим поглядом."\n',
    1638: ' divine_church_music: "Божественна церковна музика"\n',
    1639: ' divine_church_music_desc: "Багато композиторів створили свої найвеличніші твори, натхненні релігійними мотивами. Ми повинні й надалі залучати найобдарованіших творців, щоб у соборах завжди лунала прекрасна музика."\n',
    1640: ' continue_missionary_works: "Місіонерська діяльність"\n',
    1641: ' continue_missionary_works_desc: "Не варто шкодувати коштів на місіонерську діяльність. Нехай якомога більше людей з усіх куточків світу долучиться до католицької віри."\n',
    1643: ' protestant_invite_persecuted: "Притулок для переслідуваних"\n',
    1644: ' protestant_invite_persecuted_desc: "Наш народ пізнав істинну віру, проте багато братів страждають під гнітом тих, що заблукали. Ми повинні підтримати цих людей і прихистити їх у себе. Тут вони зможуть жити без страху і, що не менш важливо, вносити свій внесок у поповнення нашої скарбниці."\n',
    1645: ' protestant_administration_tax: "Ефективні збирачі податків"\n',
    1646: ' protestant_administration_tax_desc: "У минулому духівництво активно брало участь у зборі податків. Хоча деякі з цих структур були скасовані в ході Реформації, серед священників як і раніше є чимало людей, що добре знають свою справу і готові служити нам."\n',
    1647: ' confessio_augustana: "Нова конфесія"\n',
    1648: ' confessio_augustana_desc: "Реформація дає можливість створити нове віровчення і, що не менш важливо, сприймати критику і трансформувати його."\n',
    1649: ' devotionalism: "Релігійний запал"\n',
    1650: ' devotionalism_desc: "Нам слід відродити августинівську теологію, зробивши почуття і пориви віруючих опорою нашої віри."\n',
    1651: ' protect_the_new_faith: "Щит віри"\n',
    1652: ' protect_the_new_faith_desc: "Вороги оточують нас з усіх боків, і нам доведеться захищати свою віру від зазіхань гнобителів-папістів."\n',
    1653: ' expulsion_of_heretics: "Вигнання єретиків"\n',
    1654: ' expulsion_of_heretics_desc: "Єретики — постійне джерело проблем. Більше того, ці люди можуть очолити заколот проти правителя. Якщо відправити їх у заморські колонії, вони менше нам докучатимуть."\n',
    1655: ' repurposed_monasteries: "Переобладнання монастирів"\n',
    1656: ' repurposed_monasteries_desc: "Старі церковні землі, захоплені в ході перетворення нашої держави, стануть новими центрами виробництва і управління."\n',
    1657: ' involved_laity: "Залучення мирян"\n',
    1658: ' involved_laity_desc: "Підвищуючи залученість мирян у повсякденні справи церкви, ми сприяємо формуванню більш тісного зв\'язку народу з вірою."\n',
    1661: ' protestant_painters: "Мистецтво протестантів"\n',
    1662: ' protestant_painters_desc: "Під впливом Реформації творці дедалі частіше стали звертатися до нових сюжетів, далеких від прославлення Господа. Найнявши побільше таких талантів, ми здобудемо собі славу покровителів мистецтв."\n',
    1665: ' protestant_work_ethic: "Старанні працівники"\n',
    1666: ' protestant_work_ethic_desc: "Вплив проповідників-пуритан і пієтистів на Реформацію незаперечний. Особливу увагу вони приділяють таким чеснотам, як ощадливість і працелюбність, що допоможе нам виростити більш відповідальних і вмілих працівників."\n',
    1667: ' embrace_romanticism: "Покровительство романтизму"\n',
    1668: ' embrace_romanticism_desc: "На заході епохи Просвітництва ми не повинні забувати про привабливість романтизму. Наші творці, що працюють у цьому напрямку, здатні створювати справді великі твори мистецтва."\n',
    1669: ' wary_of_heretic_preachers: "Захист від єретиків"\n',
    1670: ' wary_of_heretic_preachers_desc: "Варто остерігатися тих, хто намагається навернути наш народ в іншу віру або повернути його до колишньої віри. Заклеймивши таких проповідників ворогами і мерзотниками, ми налаштуємо людей проти них і допоможемо їм сформувати правильний релігійний світогляд."\n',
    1671: ' protestant_innovation: "Новації протестантів"\n',
    1672: ' protestant_innovation_desc: "Оскільки наша віра народилася з протесту, ми чудово знаємо, як важливо піддавати сумніву усталені доктрини і погляди. Те ж саме можна сказати й про інші галузі знань."\n',
    1674: ' unlock_early_carrack_advance: "$n_early_carrack$"\n',
    1676: ' unlock_carrack_advance: "$n_carrack$"\n',
    1678: ' unlock_galleon_advance: "$n_galleon$"\n',
    1680: ' unlock_twodecker_advance: "$n_twodecker$"\n',
    1682: ' unlock_threedecker_advance: "$n_threedecker$"\n',
    1684: ' unlock_barque_advance: "$n_barque$"\n',
    1686: ' unlock_caravel_advance: "$n_caravel$"\n',
    1688: ' unlock_pinnace_advance: "$n_pinnace$"\n',
    1690: ' unlock_frigate_advance: "$n_frigate$"\n',
    1692: ' unlock_heavy_frigate_advance: "$n_heavy_frigate$"\n',
    1694: ' unlock_m_galley_advance: "$n_mediterrannean_galley$"\n',
    1696: ' unlock_war_galley_advance: "$n_war_galley$"\n',
    1698: ' unlock_galleass_advance: "$n_galleass$"\n',
    1700: ' unlock_xebec_advance: "$n_xebec$"\n',
    1702: ' unlock_hulk_advance: "$n_hulk$"\n',
    1704: ' unlock_cog_advance: "$n_cog$"\n',
    1706: ' unlock_flute_advance: "$n_flute$"\n',
    1708: ' unlock_brig_advance: "$n_brig$"\n',
    1710: ' unlock_merchantman_advance: "$n_merchantman$"\n',
    1712: ' unlock_eastindiaman_advance: "$n_eastindiaman$"\n',
    1714: ' unlock_ship_of_the_line_advance: "$n_ship_of_the_line$"\n',
    1716: ' unlock_war_galleon: "$n_war_galleon$"\n',
    1718: ' unlock_archipelago_frigate: "$n_archipelago_frigate$"\n',
    1720: ' unlock_cakradonya: "$n_cakradonya$"\n',
    1722: ' unlock_galiot: "$n_galiot$"\n',
    1724: ' unlock_baochuan: "$n_baochuan$"\n',
    1726: ' unlock_sekibune: "$n_sekibune$"\n',
    1728: ' unlock_atakebune: "$n_atakebune$"\n',
    1730: ' unlock_bomb_ketch: "$n_bomb_ketch$"\n',
    1732: ' unlock_dhow: "$n_dhow$"\n',
    1734: ' unlock_long_fada: "$n_long_fada$"\n',
    1737: ' unlock_feudal_levy_advance: "$a_feudal_levy$"\n',
    1739: ' unlock_peasant_levy_advance: "$a_peasant_levy$"\n',
    1741: ' unlock_matchlock_levy: "$a_matchlock_levy$"\n',
    1743: ' unlock_flintlock_levy: "$a_flintlock_levy$"\n',
    1745: ' militiamen_advance: "$a_militiamen$"\n',
    1747: ' conscription_advance: "$a_conscripts$"\n',
    1749: ' unlock_footmen_advance: "$a_footmen$"\n',
    1751: ' unlock_men_at_arms_advance: "$a_men_at_arms$"\n',
    1753: ' unlock_reformed_crusader_knights_advance: "$a_late_crusader_knights$"\n',
    1755: ' unlock_arquebusiers_advance: "$a_arquebusiers$"\n',
    1757: ' unlock_horsemen_advance: "$a_horsemen$"\n',
    1759: ' unlock_lancers_advance: "$a_lancers$"\n',
    1761: ' unlock_caracole_advance: "$a_caracole$"\n',
    1763: ' unlock_hussars_advance: "$a_hussars$"\n',
    1765: ' unlock_dragoons_advance: "$a_dragoons$"\n',
    1767: ' unlock_cuirassiers_advance: "$a_cuirassiers$"\n',
    1769: ' unlock_houfnice_advance: "$a_houfnice$"\n',
    1771: ' unlock_falconet_advance: "$a_falconet$"\n',
    1773: ' unlock_chambered_cannon_advance: "$a_chambered_cannon$"\n',
    1775: ' unlock_royal_mortar_advance: "$a_royal_mortar$"\n',
    1777: ' unlock_flying_battery_advance: "$a_flying_battery$"\n',
    1779: ' unlock_early_longbowmen_advance: "$a_early_longbowmen$"\n',
    1781: ' unlock_longbowmen_advance: "$a_longbowmen$"\n',
    1783: ' unlock_late_longbowmen_advance: "$a_late_longbowmen$"\n',
    1785: ' unlock_supply_carts: "$a_supply_carts$"\n',
    1787: ' unlock_supply_convoy: "$a_supply_convoy$"\n',
    1789: ' unlock_baggage_train: "$a_baggage_train$"\n',
    1791: ' unlock_wagon_train: "$a_wagon_train$"\n',
    1793: ' unlock_logistics_corps: "$a_logistics_corps$"\n',
    1795: ' unlock_archers_advance: "$a_archers$"\n',
    1797: ' unlock_crossbowmen_advance: "$a_crossbowmen$"\n',
    1799: ' unlock_halberdiers_advance: "$a_halberdiers$"\n',
}

# Читання файлу
with io.open(FILE_PATH, 'r', encoding='utf-8-sig') as f:
    lines = f.readlines()

# Застосування перекладів
for line_num, translation in translations.items():
    if line_num <= len(lines):
        lines[line_num - 1] = translation

# Збереження файлу
with io.open(FILE_PATH, 'w', encoding='utf-8-sig') as f:
    f.writelines(lines)

print(f"Переклад рядків 1600-1800 завершено. Оброблено {len(translations)} рядків.")
