#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Переклад рядків 1001-1200 файлу advances_l_english.yml
"""

import io

# Словник перекладів
translations = {
    1001: ' state_efficiency: "Місцева інфраструктура"\n',
    1002: ' state_efficiency_desc: "Приділяючи увагу справам держави в цілому, не слід забувати про потреби місцевих законодавців і пристав."\n',
    1003: ' efficient_mining: "Ефективна гірнича промисловість"\n',
    1004: ' efficient_mining_desc: "Щоб на наші ринки надходили якісні метали, ми видамо указ, який постановляє вдосконалити методи їхнього видобутку."\n',
    1005: ' efficient_construction_plans: "Ефективні будівельні проекти"\n',
    1006: ' efficient_construction_plans_desc: "Завдяки практичному підходу до будівництва ми зможемо виконувати роботи, не економлячи на якості."\n',
    1007: ' expanded_infrastructure_network: "Розширена інфраструктурна мережа"\n',
    1008: ' expanded_infrastructure_network_desc: "Дороги, що зв\'язують між собою різні куточки нашої держави, — це важливий фактор фінансового і адміністративного благополуччя. Їх необхідно постійно покращувати і підтримувати в чудовому стані."\n',
    1009: ' fort_logistics: "Логістика укріплень"\n',
    1010: ' fort_logistics_desc: "Система укріплень повинна бути в ідеальному порядку — з точки зору і конструкції, і постачання. У довгостроковій перспективі це дозволить нам заощадити."\n',
    1011: ' regulation_bureau: "Відділ з регулювання"\n',
    1012: ' regulation_bureau_desc: "До юрисдикції цього законодавчого органу входить контроль за дотриманням законів, що стосуються інфляції, а також управління провінціями на місцевому рівні."\n',
    1013: ' more_merchants_age_of_trad: "Купецькі гільдії"\n',
    1014: ' more_merchants_age_of_trad_desc: "Гільдії здавна вважаються одним зі стовпів нашої економіки, однак до них входять переважно ремісники, ніж купці. Потрібно заохочувати купців засновувати власні гільдії, і тоді втілювати в життя різні комерційні задуми стане простіше."\n',
    1015: ' construction_speed_traditions: "Майстри-каменярі"\n',
    1016: ' construction_speed_traditions_desc: "Будівництво має йти безперервно; неприпустимо, щоб у селах і містечках панувала лінь. Найнявши майстра-каменяра, який буде завідувати будівельними роботами, ми значно прискоримо розвиток держави."\n',
    1017: ' diplomatic_capacity_traditions: "Розширені архіви"\n',
    1018: ' diplomatic_capacity_traditions_desc: "Постійна дипломатична робота неможлива без діловодства і складання докладних описів усіх, з ким ми маємо справу."\n',
    1019: ' rural_rgo_traditions: "Розчищення місцевості"\n',
    1020: ' rural_rgo_traditions_desc: "Щоб економічні можливості нашої держави стали ширшими, доведеться покорити її далекі рубежі. Так ми не тільки впораємося з перенаселенням, але й заодно знайдемо корисне застосування силам нових поселенців."\n',
    1021: ' matchlock_gun: "Ранні мисливські рушниці"\n',
    1022: ' matchlock_gun_desc: "Доопрацювання рушниць, які виробляють наші зброярі, піде на користь мисливцям: вони зможуть добувати більше хутра і м\'яса."\n',
    1023: ' flintlock_gun: "Покращені мисливські рушниці"\n',
    1024: ' flintlock_gun_desc: "Нові кременеві рушниці і спеціальні мисливські кулі ще більше спростять нелегку працю наших мисливців."\n',
    1025: ' long_rifle: "Полювання з довгоствольними гвинтівками"\n',
    1026: ' long_rifle_desc: "Спеціальні мисливські гвинтівки з довгими стволами стануть зручним і надійним інструментом для здобувачів хутра і м\'яса."\n',
    1027: ' dyes_workshop_advance: "$dyes_workshop$"\n',
    1028: ' dyes_workshop_advance_desc: "$dyes_workshop_desc$"\n',
    1029: ' dyesworks_advance: "$dyesworks$"\n',
    1030: ' dyesworks_advance_desc: "$dyesworks_desc$"\n',
    1031: ' dyes_mill_advance: "$dyes_mill$"\n',
    1032: ' dyes_mill_advance_desc: "$dyes_mill_desc$"\n',
    1033: ' glass_workshop_advance: "$glass_workshop$"\n',
    1034: ' glass_workshop_advance_desc: "$glass_workshop_desc$"\n',
    1035: ' furniture_workshop_advance: "$furniture_workshop$"\n',
    1036: ' furniture_workshop_advance_desc: "$furniture_workshop_desc$"\n',
    1037: ' glass_mill_advance: "$glass_mill$"\n',
    1038: ' glass_mill_advance_desc: "$glass_mill_desc$"\n',
    1039: ' weapon_workshop_advance: "$weapon_workshop$"\n',
    1040: ' weapon_workshop_advance_desc: "$weapon_workshop_desc$"\n',
    1041: ' cannon_workshop_advance: "$cannon_workshop$"\n',
    1042: ' cannon_workshop_advance_desc: "$cannon_workshop_desc$"\n',
    1043: ' naval_supplies_workshop_advance: "$naval_supplies_workshop$"\n',
    1044: ' naval_supplies_workshop_advance_desc: "$naval_supplies_workshop_desc$"\n',
    1045: ' saltpeter_workshop_advance: "$saltpeter_workshop$"\n',
    1046: ' saltpeter_workshop_advance_desc: "$saltpeter_workshop_desc$"\n',
    1047: ' putrefaction_mill_advance: "$putrefaction_mill$"\n',
    1048: ' putrefaction_mill_advance_desc: "$putrefaction_mill_desc$"\n',
    1049: ' naval_supplies_mill_advance: "$naval_supplies_mill$"\n',
    1050: ' naval_supplies_mill_advance_desc: "$naval_supplies_mill_desc$"\n',
    1051: ' fine_cloth_workshop_advance: "$fine_cloth_workshop$"\n',
    1052: ' fine_cloth_workshop_advance_desc: "$fine_cloth_workshop_desc$"\n',
    1053: ' cloth_workshop_advance: "$cloth_workshop$"\n',
    1054: ' cloth_workshop_advance_desc: "$cloth_workshop_desc$"\n',
    1055: ' distillers_workshop_advance: "$distillers_workshop$"\n',
    1056: ' distillers_workshop_advance_desc: "$distillers_workshop_desc$"\n',
    1057: ' beer_workshop_advance: "$beer_workshop$"\n',
    1058: ' beer_workshop_advance_desc: "$beer_workshop_desc$"\n',
    1059: ' brewery_mill_advance: "$brewery_mill$"\n',
    1060: ' brewery_mill_advance_desc: "$brewery_mill_desc$"\n',
    1061: ' distiller_mill_advance: "$distiller_mill$"\n',
    1062: ' distiller_mill_advance_desc: "$distiller_mill_desc$"\n',
    1063: ' tools_workshop_advance: "$tools_workshop$"\n',
    1064: ' tools_workshop_advance_desc: "$tools_workshop_desc$"\n',
    1065: ' pottery_workshop_advance: "$pottery_workshop$"\n',
    1066: ' pottery_workshop_advance_desc: "$pottery_workshop_desc$"\n',
    1067: ' iron_mill_advance: "$iron_mill$"\n',
    1068: ' iron_mill_advance_desc: "$iron_mill_desc$"\n',
    1069: ' pottery_manufactory_advance: "$pottery_manufactory$"\n',
    1070: ' pottery_manufactory_advance_desc: "$pottery_manufactory_desc$"\n',
    1071: ' pottery_mill_advance: "$pottery_mill$"\n',
    1072: ' pottery_mill_advance_desc: "$pottery_mill_desc$"\n',
    1073: ' furniture_manufactory_advance: "$furniture_manufactory$"\n',
    1074: ' furniture_manufactory_advance_desc: "$furniture_manufactory_desc$"\n',
    1075: ' furniture_mill_advance: "$furniture_mill$"\n',
    1076: ' furniture_mill_advance_desc: "$furniture_mill_desc$"\n',
    1077: ' tanning_workshop_advance: "$tanning_workshop$"\n',
    1078: ' tanning_workshop_advance_desc: "$tanning_workshop_desc$"\n',
    1079: ' guns_workshop_advance: "$guns_workshop$"\n',
    1080: ' guns_workshop_advance_desc: "$guns_workshop_desc$"\n',
    1081: ' tannery_mill_advance: "$tannery_mill$"\n',
    1082: ' tannery_mill_advance_desc: "$tannery_mill_desc$"\n',
    1083: ' printing_manufactory_advance: "$printing_manufactory$"\n',
    1084: ' printing_manufactory_advance_desc: "$printing_manufactory_desc$"\n',
    1085: ' paper_manufactory_advance: "$paper_manufactory$"\n',
    1086: ' paper_manufactory_advance_desc: "$paper_manufactory_desc$"\n',
    1087: ' printing_mill_advance: "$printing_mill$"\n',
    1088: ' printing_mill_advance_desc: "$printing_mill_desc$"\n',
    1089: ' paper_mill_advance: "$paper_mill$"\n',
    1090: ' paper_mill_advance_desc: "$paper_mill_desc$"\n',
    1091: ' modern_road_advance: "$modern_road$"\n',
    1092: ' modern_road_advance_desc: "$modern_road_desc$"\n',
    1093: ' paved_road_advance: "$paved_road$"\n',
    1094: ' paved_road_advance_desc: "$paved_road_desc$"\n',
    1095: ' railroad_advance: "$railroad$"\n',
    1096: ' railroad_advance_desc: "$railroad_desc$"\n',
    1097: ' power_projection_advance_6: "Прагнення світового масштабу"\n',
    1098: ' power_projection_advance_6_desc: "З кількох держав, що злилися воєдино, утворилися великі держави, які користуються величезною владою на своїх континентах. Однак цього їм мало: свій вплив вони хочуть поширити ще далі."\n',
    1099: ' enlightened_court: "Освічений двір"\n',
    1100: ' enlightened_court_desc: "Кожен сучасний двір сьогодні побудований на принципах епохи Відродження, які, як відомо, виховують виключно освічених і освічених людей. Завдяки цьому ми здатні досягти більшого, докладаючи менше зусиль."\n',
    1101: ' government_size_revolutions: "Сучасне представництво"\n',
    1102: ' government_size_revolutions_desc: "Завдяки появі нових різновидів народного представництва сучасна влада може вирішувати ще більше питань."\n',
    1103: ' global_supply_limit_modifier_advance_6: "Планування постачання у військових походах"\n',
    1104: ' global_supply_limit_modifier_advance_6_desc: "Постачати сучасні війська стає все складніше: їхня чисельність така велика, що в довгих походах сьогодні можуть брати участь відразу кілька армій з сотень тисяч солдатів."\n',
    1105: ' rgo_size_advance_revolutions: "Паровий двигун"\n',
    1106: ' rgo_size_advance_revolutions_desc: "Сила пари, що приводить у рух механізми, була відома ще в давнину, однак повністю розкрити її потенціал вдалося лише недавно: нові відкриття в галузі фізики і математики привели до створення парових двигунів, без яких була б неможлива робота складних агрегатів. Продуктивність праці значно виросла у всіх галузях."\n',
    1107: ' military_tactics_advance_6: "Польова артилерія"\n',
    1108: ' military_tactics_advance_6_desc: "З тих пір як артилерійські частини набули рухливості, область роботи артилерії перестала бути обмеженою незмінною дальністю стрільби. Тепер на окремі ділянки фронту можна перекидати частково незалежні батареї під командуванням офіцерів-артилеристів."\n',
    1109: ' road_advance_2: "Прості дороги"\n',
    1110: ' road_advance_2_desc: "Старих примітивних доріг більше не вистачає. Транспортна система значно застаріла. Побудувавши нові дороги, ми зможемо розширити товарообіг у межах держави."\n',
    1111: ' written_alphabet: "Алфавіт"\n',
    1112: ' written_alphabet_desc: "Народ — це насамперед сукупність культурних надбань. Винахід алфавіту — лише перший крок на шляху до безсмертя, а заодно — до загальної освіти."\n',
    1113: ' codified_laws: "Офіційні звіди законів"\n',
    1114: ' codified_laws_desc: "Укладення і постанови життєво необхідні для побудови повноцінного суспільства. Щоб держава діяла ефективно і була здатна на більше, нам потрібні письмові звіди законів."\n',
    1115: ' taxation_advance: "Оподаткування"\n',
    1116: ' taxation_advance_desc: "Життя в цивілізованому суспільстві передбачає витрати на утримання центральної влади. Кошти на ці витрати, без яких неможлива робота уряду, ми будемо стягувати з ленників і громадян у вигляді податків."\n',
    1117: ' state_administration_advance: "Державний апарат"\n',
    1118: ' state_administration_advance_desc: "Оподаткування має сенс лише в тому випадку, якщо ми знаємо, хто де живе, яких законів і звичаїв дотримується. Нам необхідна повноцінна система управління державою."\n',
    1119: ' agriculture_advance: "Сільське господарство"\n',
    1120: ' agriculture_advance_desc: "Земля — найбільше джерело багатства. Вона може бути рясною і родючою. Нагодувати народ, домогтися достатку і розквіту суспільства зможе лише той, хто вміє правильно поводитися із землею."\n',
    1121: ' city_building_advance: "Міське будівництво"\n',
    1122: ' city_building_advance_desc: "Основна мета розвитку міст зосереджена на центральних районах і широкій забудові їх химерними будівлями."\n',
    1123: ' road_building: "Будівництво доріг"\n',
    1124: ' road_building_desc: "Держава, нездатна переміщувати товари, війська і людей, приречена на загибель. Навіть найпримітивніша дорожня мережа допоможе з\'єднати між собою поселення — це помітно полегшить життя простому народу."\n',
    1125: ' ship_building_advance: "Кораблебудування"\n',
    1126: ' ship_building_advance_desc: "Море обіцяє нам пригоди і незліченні багатства... а також можливість встановити нові торговельні відносини і розширити кордони держави."\n',
    1127: ' mapmaking: "Складання карт"\n',
    1128: ' mapmaking_desc: "Нанесення місцевості або цілої держави на папір або пергамент — це складне мистецтво, пов\'язане зі збором стратегічно важливих відомостей. Точне знання, де розташоване те або інше місце, не тільки допомагає нам планувати напади, але й дає розуміння, як влаштована наша власна держава. Як кажуть, знання — сила."\n',
    1129: ' standardized_coins: "Стандартизація монет"\n',
    1130: ' standardized_coins_desc: "Чим багатшою стає держава, тим більше в ній з\'являється монетних дворів. Наш народ звик до різноманітності валют, однак з підробкою монет, наприклад використанням меншої кількості благородних металів або спилюванням граней, необхідно боротися. Для цього ми введемо нові стандарти."\n',
    1131: ' humanism_ideas: "Гуманізм"\n',
    1132: ' humanism_ideas_desc: "Ставлячи людину понад усе, ми визнаємо за собою зобов\'язання постійно прагнути до невідомого і розгадувати навколишні нас таємниці, користуючись своїм найбільшим даром — розумом. Тільки освічена людина по-справжньому вільна — вона володіє свободою волі і самостійно приймає рішення. Користуючись мудрістю давніх як опорою, ми будемо розвивати людський дух і вчитися не тільки на помилках, але й на успіхах."\n',
    1133: ' legalism_advance: "Легалізм"\n',
    1134: ' legalism_advance_desc: "Правила і закони самі по собі марні. Їх слід звести воєдино, стандартизувати, а головне — зробити зрозумілими кожному. І якщо такі закони будуть дотримуватися беззаперечно, у нашій державі запанують свобода і справедливість."\n',
    1135: ' meritocracy_advance: "Меритократія"\n',
    1136: ' meritocracy_advance_desc: "Навіть найскромніший і непримітний трудівник іноді може виявити небувалі здібності — для цього не обов\'язково входити до вищих верств суспільства. Виявляти наявність таких здібностей, працелюбства і знань у цілому ми будемо за допомогою єдиних екзаменів. Вони допоможуть найгідніше виявити себе, що піде лише на користь народу."\n',
    1137: ' cathedral_advance: "Кафедральний собор"\n',
    1138: ' cathedral_advance_desc: "Кафедральний собор — це найважливіший християнський храм. Тут знаходиться кафедра, на якій восідає єпископ. Навіть найкрасивіша церква навряд чи може тягатися з величчю неймовірно величезних, багато прикрашених кафедральних соборів."\n',
    1139: ' infiltrate_administration: "[Concept(\'infiltrate_administration\',\'Впровадження у владу\')|e]"\n',
    1140: ' supportrebels: "[Concept(\'support_rebels\',\'Підтримка заколотників\')|e]"\n',
    1141: ' infiltrate_administration_advance: "Впровадження у владу"\n',
    1142: ' infiltrate_administration_advance_desc: "Результат міжнародних конфліктів вирішується не тільки на полі бою, але й у кулуарах. Знання планів противника допомагає вигравати війни. Ми повинні впровадити своїх агентів в адміністрацію інших держав, щоб вони передавали нам коштовну інформацію."\n',
    1143: ' newspapers_advance: "Газети"\n',
    1144: ' newspapers_advance_desc: "Ідея публікації оголошень на табличках і сувоях не нова, однак попит на політичну, військову і економічну інформацію постійно зростає. $printing_press$ робить її набагато доступнішою. Регулярно випускаючи друковані аркуші з оглядом поточних подій, ми задовольнимо потребу населення в новинах."\n',
    1145: ' feudal_de_jure_law_advance: "$feudal_de_jure_law$"\n',
    1146: ' feudal_de_jure_law_advance_desc: "Терміном #italic «де-юре»#! прийнято називати юридично визнані правила незалежно від їхньої відповідності реальному стану справ. На цьому принципі було засноване все феодальне суспільство."\n',
    1147: ' semi_salic_law_advance: "$semi_salic_law$"\n',
    1148: ' semi_salic_law_advance_desc: "$salic_law$ проголошує, що успадковувати трон можуть тільки чоловіки. Якщо у монарха не виявиться синів, така практика може призвести до кризи престолонаслідування. Щоб уникнути його, право спадкування слід поширити і на жінок — звичайно, за відсутності підходящих претендентів чоловічої статі."\n',
    1149: ' republican_foundation_law_advance: "$republican_foundation_law$"\n',
    1150: ' republican_foundation_law_advance_desc: "$republican_foundation_law_desc$"\n',
    1151: ' republican_election_law_advance: "$republican_election_law$"\n',
    1152: ' republican_election_law_advance_desc: "$republican_election_law_desc$"\n',
    1153: ' republican_electorate_law_advance: "$republican_electorate_law$"\n',
    1154: ' republican_electorate_law_advance_desc: "$republican_electorate_law_desc$"\n',
    1155: ' republican_power_law_advance: "$republican_power_law$"\n',
    1156: ' republican_power_law_advance_desc: "$republican_power_law_desc$"\n',
    1157: ' principle_of_administration_law_advance: "Закон про принцип управління"\n',
    1158: ' principle_of_administration_law_advance_desc: "Природний розвиток і ускладнення нашої державної машини вимагає прийняття нових законів, що регулюють роботу адміністрації."\n',
    1159: ' monarchy_reform_traditions_advance: "Традиції монархічних принципів"\n',
    1160: ' monarchy_reform_traditions_advance_desc: "Владу не можна довіряти кому попало. Концентруючи вплив у руках правителя, ми гарантуємо порядок і стабільність на всій підконтрольній монархії території."\n',
    1161: ' republic_reform_traditions_advance: "Традиції республіканських принципів"\n',
    1162: ' republic_reform_traditions_advance_desc: "Розподіл влади є основою існування здорової республіки. Створення докладного звіду законів, що регулює вибори, дозволить нам підвищити стабільність і приборкати корупцію."\n',
    1163: ' blockade_tactics: "Тактика блокади"\n',
    1164: ' blockade_tactics_desc: "Застосовуючи певні бойові порядки і організовуючи морські патрулі в районі ворожих портів, ми ефективніше перекриємо постачання противника і скоротимо тривалість облог."\n',
    1165: ' recovery_efforts: "Післявоєнне відновлення"\n',
    1166: ' recovery_efforts_desc: "Війна — жорстока господиня, що сіє безліч бід і руйнувань. Зосередивши зусилля на допомозі нашому народу, ми прискоримо відновлення держави."\n',
    1167: ' naval_initiative_ren: "Тактика розгортання"\n',
    1168: ' naval_initiative_ren_desc: "Відомо, що перехоплення ініціативи і швидка мобілізація є першими кроками до перемоги. Вивчення і впровадження тактики розгортання дозволять нам досягти прогресу в цій галузі."\n',
    1169: ' army_initiative_ren: "Випереджальний удар"\n',
    1170: ' army_initiative_ren_desc: "Поєднання елемента несподіванки і ударів на випередження практично завжди приносить перемогу. Впровадження ініціативи в армії — чудовий спосіб зберегти перевагу перед противниками."\n',
    1171: ' law_making_renaissance: "Перегляд законів"\n',
    1172: ' law_making_renaissance_desc: "Часи змінюються. Закони, за якими жили покоління наших предків, не завжди застосовні в сучасному житті. Щоб не відстати від прогресу, слід постійно переглядати і адаптувати законодавство."\n',
    1173: ' subject_integration: "Консолідація титулів"\n',
    1174: ' subject_integration_desc: "Нашим інтересам служать багато формально незалежних держав, але, щоб повною мірою користуватися їхніми землями і ресурсами, треба зібрати їхні титули під єдиною короною. Зрештою, кількість титулів підвищує статус монарха."\n',
    1175: ' rgo_construction_ren: "Розвиток інфраструктури"\n',
    1176: ' rgo_construction_ren_desc: "Земля і люди — плоть і кров нашої держави. Зусилля, вкладені нами в розвиток інфраструктури і поліпшення життя простих людей, окупляться десятикратно."\n',
    1177: ' naval_repair_ren: "Щільна підгонка обшивки"\n',
    1178: ' naval_repair_ren_desc: "Всім відомо, що діри в корпусі судна ведуть до його затоплення. Нові технології кораблебудування дозволяють щільніше підганяти дошки обшивки одна до одної, що знижує ймовірність течі і полегшує боротьбу за виживання при пошкодженні корпусу."\n',
    1179: ' linked_armies_advance: "Кур\'єрська служба"\n',
    1180: ' linked_armies_advance_desc: "Координація дій між підрозділами необхідна для належного функціонування армії. Організувавши надійну систему передачі повідомлень між полководцями і командирами ввірених їм загонів, ми підвищимо згуртованість військ і прискоримо їхню реакцію на зміну обстановки."\n',
    1181: ' regular_levy_training: "Інструктори ополчення"\n',
    1182: ' regular_levy_training_desc: "Ополчення за визначенням підготовлене гірше професійних військових, але це не значить, що нам слід посилати на війну ненавчений збір. Призначивши інструкторів з найдосвідченіших загонів і виділивши час на обов\'язкове навчання, ми перетворимо вчорашніх селян на справжніх воїнів."\n',
    1183: ' court_accounting: "Придворна бухгалтерія"\n',
    1184: ' court_accounting_desc: "Двір монарха — це обличчя держави; його багатство символізує процвітання всієї держави. Але це зовсім не означає, що витрати на його утримання можуть перевищувати можливості казни. Слід ввести суворий облік усіх придворних витрат."\n',
    1185: ' lead_ore_dressing: "Збагачення свинцевих руд"\n',
    1186: ' lead_ore_dressing_desc: "У процесі збагачення свинцева руда подрібнюється і промивається від глини, каменів і іншої порожньої породи."\n',
    1187: ' bole_smelting: "Плавка на пагорбах"\n',
    1188: ' bole_smelting_desc: "Ця технологія виплавки свинцю на відкритому повітрі дозволяє використовувати сильний вітер, що постійно дує на вершинах пагорбів."\n',
    1189: ' cupola_smelting: "Плавка у вагранці"\n',
    1190: ' cupola_smelting_desc: "Ця технологія виплавки заліза в печі циліндричної форми не тільки здешевлює і спрощує процес, але й дозволяє зробити його безперервним."\n',
    1191: ' faster_levy_recruitment: "Обов\'язкові тренування зі зброєю"\n',
    1192: ' faster_levy_recruitment_desc: "Кожен селянин чоловічої статі зобов\'язаний регулярно вправлятися у володінні списом або луком, щоб не бути тягарем у разі призову до ополчення."\n',
    1193: ' merchant_power_from_maritime_discovery_advance: "Купецькі гільдії"\n',
    1194: ' merchant_power_from_maritime_discovery_advance_desc: "Об\'єднання в гільдії дозволить нашим купцям організовувати свою діяльність, обмінюватися відомостями про вигідні торговельні шляхи і підтримувати один одного при торгівлі на зарубіжних ринках."\n',
    1195: ' merchant_power_from_maritime_reformation_advance: "Торговельні компанії"\n',
    1196: ' merchant_power_from_maritime_reformation_advance_desc: "Збільшення ризиків і витрат, пов\'язаних з торгівлею в заморських колоніях, вимагає створення купецьких асоціацій, що дозволяють розділити цей тягар."\n',
    1197: ' merchant_power_from_maritime_absolutism_advance: "Торговельна палата"\n',
    1198: ' merchant_power_from_maritime_absolutism_advance_desc: "З поширенням нових ідей у комерції і економіці місцеві підприємці стали об\'єднуватися в ділові мережі для захисту своїх прав і інтересів від політичних структур і іноземного впливу."\n',
    1199: ' paper_guild_fiber_pulp_maintenance_advance: "$paper_guild_fiber_pulp_maintenance$"\n',
    1200: ' paper_guild_fiber_pulp_maintenance_advance_desc: "Використання таких рослинних матеріалів, як коноплі і шовковиця, зробило папір доступним у всьому світі, однак разом з ціною знизилася і його якість."\n',
}

# Читаємо файл
file_path = '/Users/furmonenko/Desktop/eu5-ukrainian-localization/main_menu/localization/english/advances_l_english.yml'

with io.open(file_path, 'r', encoding='utf-8-sig') as f:
    lines = f.readlines()

# Застосовуємо переклади
for line_num, translation in translations.items():
    if line_num <= len(lines):
        lines[line_num - 1] = translation

# Записуємо назад
with io.open(file_path, 'w', encoding='utf-8-sig') as f:
    f.writelines(lines)

print(f"✓ Перекладено рядки 1001-1200 ({len(translations)} рядків)")
