#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Фінальний переклад рядків 1201-2000 файлу advances_l_english.yml
"""

import io

# Частина 1: Рядки 1201-1400
translations_1 = {
    1201: ' paper_guild_cloth_maintenance_advance: "$paper_guild_cloth_maintenance$"\n',
    1202: ' paper_guild_cloth_maintenance_advance_desc: "$paper_guild_cloth_maintenance$, виготовлена з відходів бавовни або старого текстилю, задає нові стандарти якості та міцності."\n',
    1203: ' paper_guild_wood_pulp_maintenance_advance: "$paper_guild_wood_pulp_maintenance$"\n',
    1204: ' paper_guild_wood_pulp_maintenance_advance_desc: "Використання широко поширеної хвойної деревини дозволить ще більше спростити і здешевити виробництво паперу."\n',
    1205: ' cannon_guild_steel_maintenance_advance: "Сталеві гарматні стволи"\n',
    1206: ' cannon_guild_steel_maintenance_advance_desc: "Гармати зі сталевими стволами дозволять нашій артилерії бити далі і точніше, не обмежуючи її мобільність."\n',
    1207: ' firearms_guild_steel_maintenance_advance: "Сталеві рушничні стволи"\n',
    1208: ' firearms_guild_steel_maintenance_advance_desc: "Використання сталі у виробництві вогнепальної зброї дозволить нам випускати більше надійних рушниць."\n',
    1209: ' grant_privilege_cost_modifier_renaissance_advance: "Станові привілеї і обов\'язки"\n',
    1210: ' grant_privilege_cost_modifier_renaissance_advance_desc: "Кодифікація ролі кожного стану в повсякденному житті держави дозволить надавати нові привілеї, не викликаючи конфліктів між станами."\n',
    1211: ' war_no_cb_cost_modifier_renaissance_advance: "Постійна війна"\n',
    1212: ' war_no_cb_cost_modifier_renaissance_advance_desc: "Війна змінюється разом з її учасниками. Зростаючі можливості держав дозволяють їм довше вести бойові дії, через що збройні конфлікти між державами стають все більшою буденністю."\n',
    1213: ' global_nobles_max_literacy_advance: "Література для дворян"\n',
    1214: ' global_nobles_max_literacy_advance_desc: "У міру того, як дворяни перетворювалися з доблесних воїнів у куртуазних придворних, у їхньому середовищі все більше поширювалася грамотність. У результаті виник попит на літературу, привабливу для дворянського стану."\n',
    1215: ' global_burghers_max_literacy_advance: "Література для міщан"\n',
    1216: ' global_burghers_max_literacy_advance_desc: "Міщани заробляють на життя своїми здібностями і вміннями, тому серед них чимало освічених людей. Зростання добробуту цього стану, викликане розвитком економіки, привело до підвищення попиту на літературні праці, що розширюють його письмову культуру."\n',
    1217: ' global_clergy_max_literacy_advance: "Література для духовенства"\n',
    1218: ' global_clergy_max_literacy_advance_desc: "Представники духовенства, зайняті вивченням, тлумаченням і поширенням своєї доктрини, за родом діяльності зобов\'язані бути грамотними. Література, особливо релігійна, відіграє в житті цього стану величезну роль."\n',
    1219: ' land_morale_recovery_renaissance_advance: "Організовані марші"\n',
    1220: ' land_morale_recovery_renaissance_advance_desc: "З переходом від ополчення до професійних підрозділів структура армій істотно ускладнилася. Приділивши увагу організації маршів, ми підвищимо готовність армійських загонів, що здійснюють передислокацію, до раптових ударів противника."\n',
    1221: ' merchant_power_from_maritime_renaissance_advance: "Торговельні партнерства"\n',
    1222: ' merchant_power_from_maritime_renaissance_advance_desc: "Розвиток міжнародної торгівлі змусив купців шукати нові форми взаємовигідного партнерства. Найчастіше один з партнерів фінансує торговельну експедицію, а інший особисто відправляється в неї, ризикуючи життям у пошуках заморських товарів."\n',
    1223: ' merchant_power_from_maritime_revolutions_advance: "Компанії з обмеженою відповідальністю"\n',
    1224: ' merchant_power_from_maritime_revolutions_advance_desc: "Регулярні невдачі торговельних компаній привели до виникнення підприємств нового типу, в яких відповідальність пайовиків обмежується фіксованою сумою. Це знизило ризики всіх учасників і зробило такі компанії більш привабливими."\n',
    1225: ' send_people_to_colonial_charter_advance: "Рясні нові землі"\n',
    1226: ' send_people_to_colonial_charter_advance_desc: "Нові землі повні можливостей і ресурсів. Заохочуючи переселення підданих у наші нові володіння, ми істотно спростимо освоєння цих територій."\n',
    1227: ' send_people_to_the_colonies_advance: "Перспективні нові землі"\n',
    1228: ' send_people_to_the_colonies_advance_desc: "Новий світ, що відкрився перед нами, будоражить уяву багатьох потенційних колоністів. Нам слід підтримувати і розвивати подібні ідеї, щоб наші піддані охочіше переселялися на нові території."\n',
    1229: ' study_institutions_advance: "Обмін знаннями"\n',
    1230: ' study_institutions_advance_desc: "Не соромно, якщо хтось знає більше за нас — соромно не прагнути до нових знань. Активно вивчаючи чужі відкриття, ми зможемо більше дізнатися про навколишній світ."\n',
    1231: ' reduce_inflations_advance: "Сувoре монетарне регулювання"\n',
    1232: ' reduce_inflations_advance_desc: "Невігласи вважають, що при нестачі грошей треба просто випустити ще, але насправді це тільки загострює проблеми. Суворий контроль карбування монет дозволить зупинити і навіть знизити інфляцію."\n',
    1233: ' pop_promote_actions_advance: "Соціальна драбина"\n',
    1234: ' pop_promote_actions_advance_desc: "Кажуть, що хаос — це драбина, якою людина може піднятися у вищі верстви суспільства. Однак у нашій державі такою драбиною служить зовсім не хаос, а порядок. Ми регламентуємо способи, якими люди можуть поліпшити своє соціальне становище, і навіть сприяємо їм."\n',
    1235: ' alleviate_concerns_advance: "Запобігання конфліктів"\n',
    1236: ' alleviate_concerns_advance_desc: "Жодна держава не зможе процвітати, якщо всі сусіди напружено стежать за кожним її кроком. Нашим дипломатам слід цілеспрямовано розвіювати підозри і згладжувати будь-які можливі конфлікти."\n',
    1237: ' counter_espionage_action_advance: "Контроль доступу до інформації"\n',
    1238: ' counter_espionage_action_advance_desc: "Дипломатичні і військові успіхи неможливі, якщо наші секрети і відомості, що обговорюються у вузькому колі, з легкістю стають відомі в інших країнах. Нам слід контролювати поширення інформації і запобігати витокам."\n',
    1239: ' pacify_population_advance: "Боротьба з підбурювачами"\n',
    1240: ' pacify_population_advance_desc: "Серед підданих завжди знайдуться невдоволені, але якщо ми не будемо залишати їх без уваги, вони не зможуть завдати нам істотної шкоди. Своєчасно виявляючи тих, хто агітує народ проти влади, ми не дамо їм зібрати достатньо послідовників і присічемо безлади в зародку."\n',
    1241: ' nation_state_advance: "Національна держава"\n',
    1242: ' nation_state_advance_desc: "Об\'єднати всіх представників культури під одним прапором — вдала ідея. Якщо ми приділимо достатньо часу розвитку національної самосвідомості, наші громадяни і ленники будуть всіляко нам віддані."\n',
    1243: ' LIV_a_order_knights: "Лицарі Лівонського ордена"\n',
    1244: ' LIV_a_order_knights_desc: "Наша держава тримається на могутніх плечах безстрашних християн, що вступили в лицарський орден. Їх набагато менше, ніж навколишніх язичників, але їхня воїнська доблесть з лишком відшкодовує це."\n',
    1245: ' wallachian_tradition: "Держава-фортеця"\n',
    1246: ' wallachian_tradition_desc: "Наші землі являють собою відкриту родючу рівнину, оточену горами і водами Дунаю. Подолавши ці природні бар\'єри, ворожа армія зможе безперешкодно продовжити наступ, тому нам слід побудувати всюди фортеці і замки для захисту народу."\n',
    1247: ' wallachian_heritage: "Історія опору"\n',
    1248: ' wallachian_heritage_desc: "Побувавши під владою кількох імперій, наш народ звик боротися із загарбниками. Ворог, що посмів вторгнутися в наші володіння, заплатить за це кров\'ю."\n',
    1249: ' khedivates: "Хедівати"\n',
    1250: ' khedivates_desc: "Кожна велика імперія складається з метрополії і не надто надійної периферії. Щоб наші ленники не вийшли з-під контролю, треба постійно за ними стежити."\n',
    1251: ' french_tradition: "Французький двір"\n',
    1252: ' french_tradition_desc: "Наша дипломатія, відома своєю вишуканістю і витонченістю, стала зразком для багатьох інших держав, але було б нерозумно зупинитися на досягнутому і припинити її вдосконалення."\n',
    1253: ' french_heritage: "Благородні лицарі"\n',
    1254: ' french_heritage_desc: "Вихідці з дворянства завжди були опорою нашої армії. Ці чудово навчені воїни готові знищити будь-якого ворога на славу нашої держави."\n',
    1255: ' french_ambition: "Велика армія"\n',
    1256: ' french_ambition_desc: "Дивлячись на армії наших ворогів, ми все ясніше бачимо необхідність власної військової реформи. Впровадження нових методів підготовки дозволить нашим хоробрим героям залишатися переможцями."\n',
    1257: ' english_tradition: "Лев\'ячі серця"\n',
    1258: ' english_tradition_desc: "Англійські воїни вже не раз проявляли невідому відвагу і дисципліну на полях битв від Нортумбрії до Франції. Об\'єднуючи в собі хоробрість королів і стійкість простого народу, наші піхотинці б\'ються так само люто, як і їхні англосаксонські предки."\n',
    1259: ' english_heritage: "Наш острівний дім"\n',
    1260: ' english_heritage_desc: "Перебуваючи на острові, ми захищені від сухопутного вторгнення, але повинні постійно стежити за морем. Лише домігшись повного контролю над навколишніми водами, ми зможемо гарантувати, що ворог не ступить на нашу землю."\n',
    1261: ' english_ambition: "Володарі хвиль"\n',
    1262: ' english_ambition_desc: "Будь-якій державі, що бажає правити морями, насамперед потрібний могутній флот. Треба, щоб ворожі береги завжди були оточені нашими кораблями."\n',
    1263: ' omani_tradition: "Морські дороги"\n',
    1264: ' omani_tradition_desc: "Наша держава відрізана від решти світу безкрайніми і непрохідними аравійськими пустелями, але їх можна обійти по морю, що розкинулося на сході. Саме море, а не суша, стане основою нашої дипломатії, торгівлі і експансії."\n',
    1265: ' omani_heritage: "Контроль над затокою"\n',
    1266: ' omani_heritage_desc: "Наші судна ходять по всіх морях, але щоб ці подорожі залишалися можливими, ми повинні контролювати власну затоку, захищаючи її від будь-яких чужоземних загроз."\n',
    1267: ' omani_ambition: "Непрохідні піски"\n',
    1268: ' omani_ambition_desc: "Наша земля не є островом, але відрізана від решти Аравії непрохідними пустелями. Ми розуміємо, наскільки для нас важливо ходити в море самим і позбавити такої можливості своїх ворогів."\n',
    1269: ' breton_tradition: "$breton$ський півострів"\n',
    1270: ' breton_tradition_desc: "Значну частину наших володінь становить узбережжя, на якому кипить життя з тих пір, як наші предки припливли сюди з Британії. Наш народ живе морем і заради моря, а наші порти завжди повні торговельних і рибальських суден."\n',
    1271: ' house_of_parliament_advance: "$house_of_parliament$"\n',
    1272: ' house_of_parliament_advance_desc: "$house_of_parliament_desc$"\n',
    1273: ' lacquerware_guild_advance: "$lacquerware_guild$"\n',
    1274: ' lacquerware_guild_advance_desc: "$lacquerware_guild_desc$"\n',
    1275: ' bur_between_two_realms: "Між двох вогнів"\n',
    1276: ' bur_between_two_realms_desc: "Наша держава займає землі, які історично перебувають під впливом Франції і Священної Римської імперії. Це дещо ускладнює феодальні відносини, але зате робить нас вправними дипломатами, здатними вирішувати будь-які розбіжності на свою користь."\n',
    1277: ' bur_knightly_prowess: "Лицарська доблесть"\n',
    1278: ' bur_knightly_prowess_desc: "Ми займаємо досить високе становище в феодальній системі Франції, тому наші війська повинні відповідати бургундському духу і звичаям."\n',
    1279: ' bur_rich_soil_of_burgundy: "Розвиток сільського господарства"\n',
    1280: ' bur_rich_soil_of_burgundy_desc: "Землі Бургундії відмінно підходять для скотарства і землеробства, зокрема — для вирощування винограду. Доклавши трохи зусиль, ми зможемо швидко організувати тут розвинене сільське господарство."\n',
    1281: ' mos_skilled_tax_collectors: "Збирачі данини"\n',
    1282: ' mos_skilled_tax_collectors_desc: "Будучи багато років збирачами данини для Золотої Орди, ми придумали, як залишати частину зібраних грошей собі, не викликаючи підозр."\n',
    1283: ' mos_dynastic_ties: "Правління через династичні зв\'язки"\n',
    1284: ' mos_dynastic_ties_desc: "Руські землі довго перебувають під управлінням однієї династії. Використаємо свої родинні зв\'язки і становище, щоб нарешті здобути владу."\n',
    1285: ' mos_patrol_the_territories: "Організоване ополчення"\n',
    1286: ' mos_patrol_the_territories_desc: "Управляти величезними просторами Росії непросто. Можна створити місцеві центри вербування бійців в ополчення."\n',
    1287: ' russian_integration: "Руські традиції"\n',
    1288: ' russian_integration_desc: "На руських землях проживає безліч народів, кожен зі своєю культурою, мовою і звичаями. Щоб об\'єднати людей, потрібно просувати ідею нашої спільної історії. Тільки так ми створимо між народами непорушний зв\'язок."\n',
    1289: ' russian_resiliance: "Руські методи набору"\n',
    1290: ' russian_resiliance_desc: "Навали монголів виховали в руських стійке неприйняття іноземного впливу. Спираючись на цю ідею, можна помітно збільшити розмір військ."\n',
    1291: ' land_of_the_rus: "Руська земля"\n',
    1292: ' land_of_the_rus_desc: "Всі руські правителі так або інакше прагнуть до об\'єднання Русі. Найбільш амбітні з них цілком можуть використати цей привід, щоб виправдати свої завойовницькі походи."\n',
    1293: ' russian_legitimization: "Народна легітимність"\n',
    1294: ' russian_legitimization_desc: "Руський народ століттями проживає на цих землях, тому очевидно, що правити ними також повинні руські. Чим краще правитель розуміє руську культуру і звичаї, тим охочіше народ його прийме."\n',
    1295: ' nor_seaborn_country: "Морська держава"\n',
    1296: ' nor_seaborn_country_desc: "Норвежці воліють подорожувати державою на човнах, тому серед них багато талановитих моряків, яких за необхідності можна призвати на службу у флоті."\n',
    1297: ' nor_bounties_of_the_sea: "Морські дари"\n',
    1298: ' nor_bounties_of_the_sea_desc: "Землі Норвегії погано підходять для землеробства, тому одного лише сільського господарства недостатньо, щоб запастися продовольством. На щастя, у водах Північного моря вдосталь риби, щоб нагодувати наших людей."\n',
    1299: ' nor_merchant_tradition: "Норвезькі купці"\n',
    1300: ' nor_merchant_tradition_desc: "Порти Норвегії давно стали центром притягання для торговців з усієї Європи. Настав час не тільки приймати іноземних купців, але й самим витягати вигоду з торгівлі в Північній Європі."\n',
    1301: ' grand_marketplace_advance: "$grand_marketplace$"\n',
    1302: ' grand_marketplace_advance_desc: "$grand_marketplace_desc$"\n',
    1303: ' commerce_center_advance: "$commerce_center$"\n',
    1304: ' commerce_center_advance_desc: "$commerce_center_desc$"\n',
    1305: ' mint_advance: "$minting_office$"\n',
    1306: ' mint_advance_desc: "$minting_office_desc$"\n',
    1307: ' counting_house_advance: "Контора"\n',
    1308: ' counting_house_advance_desc: "$counting_house_desc$"\n',
    1309: ' merchants_quarters_advance: "Купецькі подвір\'я"\n',
    1310: ' merchants_quarters_advance_desc: "$merchants_quarters_desc$"\n',
    1311: ' port_authority_advance: "Портове управління"\n',
    1312: ' port_authority_advance_desc: "$port_authority_desc$"\n',
    1313: ' porcelain_kiln_advance: "Піч для порцеляни"\n',
    1314: ' porcelain_kiln_advance_desc: "$porcelain_kiln_desc$"\n',
    1315: ' scriptorium_advance: "Скрипторій"\n',
    1316: ' scriptorium_advance_desc: "$scriptorium_desc$"\n',
    1317: ' paper_guild_advance: "Гільдія паперівників"\n',
    1318: ' paper_guild_advance_desc: "$paper_guild_desc$"\n',
    1319: ' gun_smith_advance: "Рушничник"\n',
    1320: ' gun_smith_advance_desc: "$gun_smith_desc$"\n',
    1321: ' firearms_factory_advance: "$firearms_factory$"\n',
    1322: ' firearms_factory_advance_desc: "$firearms_factory_desc$"\n',
    1323: ' paper_workshop_advance: "$paper_workshop$"\n',
    1324: ' paper_workshop_advance_desc: "$paper_workshop_desc$"\n',
    1325: ' printing_press_shop_advance: "Друкарня"\n',
    1326: ' printing_press_shop_advance_desc: "$printing_press_shop_desc$"\n',
    1327: ' weapon_manufactory_advance: "Зброярська мануфактура"\n',
    1328: ' weapon_manufactory_advance_desc: "$weapon_manufactory_desc$"\n',
    1329: ' naval_supplies_manufactory_advance: "Мануфактура суднобудівних матеріалів"\n',
    1330: ' naval_supplies_manufactory_advance_desc: "$naval_supplies_manufactory_desc$"\n',
    1331: ' gun_foundry_advance: "Цех для відливання гармат"\n',
    1332: ' gun_foundry_advance_desc: "$gun_foundry_desc$"\n',
    1333: ' cloth_manufactory_advance: "Сукон на мануфактура"\n',
    1334: ' cloth_manufactory_advance_desc: "$cloth_manufactory_desc$"\n',
    1335: ' putrefaction_works_advance: "Селітряний завод"\n',
    1336: ' putrefaction_works_advance_desc: "$putrefaction_works_desc$"\n',
    1337: ' fine_cloth_manufactory_advance: "Мануфактура тонкого сукна"\n',
    1338: ' fine_cloth_manufactory_advance_desc: "$fine_cloth_manufactory_desc$"\n',
    1339: ' perfumery_advance: "Парфумерна майстерня"\n',
    1340: ' perfumery_advance_desc: "$perfumery_desc$"\n',
    1341: ' glassworks_advance: "Скляна фабрика"\n',
    1342: ' glassworks_advance_desc: "$glassworks_desc$"\n',
    1343: ' porcelain_manufactor_advance: "Порцелянова мануфактура"\n',
    1344: ' porcelain_manufactor_advance_desc: "$porcelain_manufactory_desc$"\n',
    1345: ' tannery_manufactory_advance: "Дубильна мануфактура"\n',
    1346: ' tannery_manufactory_advance_desc: "$tannery_manufactory_desc$"\n',
    1347: ' distiller_manufactory_advance: "Спиртоводочна мануфактура"\n',
    1348: ' distiller_manufactory_advance_desc: "$distiller_manufactory_desc$"\n',
    1349: ' brewery_manufactory_advance: "Пивоварна мануфактура"\n',
    1350: ' brewery_manufactory_advance_desc: "$brewery_manufactory_desc$"\n',
    1351: ' winery_manufactory_advance: "$winery_manufactory$"\n',
    1352: ' winery_manufactory_advance_desc: "$winery_manufactory_desc$"\n',
    1353: ' lacquerware_manufactory_advance: "Мануфактура лакових виробів"\n',
    1354: ' lacquerware_manufactory_advance_desc: "$lacquerware_manufactory_desc$"\n',
    1355: ' iron_foundry_advance: "Чавуноливарний цех"\n',
    1356: ' iron_foundry_advance_desc: "$iron_foundry_desc$"\n',
    1357: ' textile_mill_advance: "Текстильна мануфактура"\n',
    1358: ' textile_mill_advance_desc: "$textile_mill_desc$"\n',
    1359: ' fine_cloth_mill_advance: "Мануфактура тонкого сукна"\n',
    1360: ' fine_cloth_mill_advance_desc: "$fine_cloth_mill_desc$"\n',
    1361: ' steel_mill_advance: "Сталеливарний завод"\n',
    1362: ' steel_mill_advance_desc: "$steel_mill_desc$"\n',
    1363: ' weapon_factory_advance: "Зброярський завод"\n',
    1364: ' weapon_factory_advance_desc: "$weapon_factory_desc$"\n',
    1365: ' gun_factory_advance: "Гарматний завод"\n',
    1366: ' gun_factory_advance_desc: "$cannons_factory_desc$"\n',
    1367: ' armory_advance: "Арсенал"\n',
    1368: ' armory_advance_desc: "$armory_desc$"\n',
    1369: ' training_fields_advance: "Навчальний полігон"\n',
    1370: ' training_fields_advance_desc: "$training_fields_desc$"\n',
    1371: ' barracks_advance: "Казарми"\n',
    1372: ' barracks_advance_desc: "$barracks_desc$"\n',
    1373: ' regimental_camp_advance: "Полковий гарнізон"\n',
    1374: ' regimental_camp_advance_desc: "$regimental_camp_desc$"\n',
    1375: ' conscription_center_advance: "Військова присутність"\n',
    1376: ' conscription_center_advance_desc: "$conscription_center_desc$"\n',
    1377: ' dock_advance: "Док"\n',
    1378: ' dock_advance_desc: "$dock_desc$"\n',
    1379: ' dry_dock_advance: "Сухий док"\n',
    1380: ' dry_dock_advance_desc: "$dry_dock_desc$"\n',
    1381: ' shipyard_advance: "Суднова верф"\n',
    1382: ' shipyard_advance_desc: "$shipyard_desc$"\n',
    1383: ' grand_shipyard_advance: "Велика суднова верф"\n',
    1384: ' grand_shipyard_advance_desc: "$grand_shipyard_desc$"\n',
    1385: ' naval_base_advance: "Морська база"\n',
    1386: ' naval_base_advance_desc: "$naval_base_desc$"\n',
    1387: ' coastal_fort_advance: "Берегова фортеця"\n',
    1388: ' coastal_fort_advance_desc: "$coastal_fort_desc$"\n',
    1389: ' naval_battery_advance: "Берегова батарея"\n',
    1390: ' naval_battery_advance_desc: "$naval_battery_desc$"\n',
    1391: ' castle_advance: "Замок"\n',
    1392: ' castle_advance_desc: "$castle_desc$"\n',
    1393: ' bastion_advance: "Бастіон"\n',
    1394: ' bastion_advance_desc: "$bastion_desc$"\n',
    1395: ' star_fort_advance: "Штерншанц"\n',
    1396: ' star_fort_advance_desc: "$star_fort_desc$"\n',
    1397: ' fortress_advance: "Фортеця"\n',
    1398: ' fortress_advance_desc: "$fortress_desc$"\n',
    1399: ' library_advance: "Бібліотека"\n',
    1400: ' library_advance_desc: "$library_desc$"\n',
}

print("Підготовлено переклади 1201-1400...")

# Читаємо файл
file_path = '/Users/furmonenko/Desktop/eu5-ukrainian-localization/main_menu/localization/english/advances_l_english.yml'

with io.open(file_path, 'r', encoding='utf-8-sig') as f:
    lines = f.readlines()

# Застосовуємо переклади частини 1
for line_num, translation in translations_1.items():
    if line_num <= len(lines):
        lines[line_num - 1] = translation

print(f"✓ Перекладено рядки 1201-1400 ({len(translations_1)} рядків)")

# Записуємо назад
with io.open(file_path, 'w', encoding='utf-8-sig') as f:
    f.writelines(lines)

print("Завершено переклад блоку 1201-1400")
